### ISSUE TITLE
Need help to make that task available again on git hub

### ISSUE THREAD

**Issue by matthieupetite** [GitTools/actions#108]
Dear all, I had an issue with that task. Everything was working as expected few days ago but today I am facing a new issue on my github action.

`  "InformationalVersion":"0.2.0-contact.1+11.Branch.feature-contact.Sha.4020174ba02f00f22476726e1d8df5f0e9010d6b",
  "BranchName":"feature/contact",
  "EscapedBranchName":"feature-contact",
  "Sha":"4020174ba02f00f22476726e1d8df5f0e9010d6b",
  "ShortSha":4020174,
  "NuGetVersionV2":"0.2.0-contact0001",
  "NuGetVersion":"0.2.0-contact0001",
  "NuGetPreReleaseTagV2":"contact0001",
  "NuGetPreReleaseTag":"contact0001",
  "VersionSourceSha":"182f445bd92ecd014dfe3f832d61a5bea9e4361e",
  "CommitsSinceVersionSource":11,
  "CommitsSinceVersionSourcePadded":"0011",
  "CommitDate":"2020-05-06"
}
(node:2681) UnhandledPromiseRejectionWarning: TypeError: (e || "").replace is not a function
    at /home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:943
    at s.toString (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:1005)
    at o (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:372)
    at Object.t.issue (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:432)
    at c (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:9:741)
    at Object.t.setFailed (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:9:1482)
    at h.setFailed (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:308:1902)
    at Object.<anonymous> (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:336:1575)
    at Generator.next (<anonymous>)
    at s (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:336:170)
(node:2681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Here is my configuration file for the pipeline

`steps:
            - uses: actions/checkout@v2
            - name: Fetch all history for all tags and branches
              run: |
                  git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git fetch --prune --unshallow
            - name: Install GitVersion
              uses: gittools/actions/gitversion/setup@v0.9.2
              with:
                  versionSpec: "5.2.x"
            - name: Use GitVersion
              id: gitversion # step id used as reference for output values
              uses: gittools/actions/gitversion/execute@v0.9.2`

did you have any idea on that ? Tanks a lot in advance...

**Comment by arturcic** [comment]
can you use versioin 0.9.3 instead?

**Comment by matthieupetite** [comment]
@arturcic Thanks a lot, the upgrade does the job... Big thanks for the tips ;)

**Comment by arturcic** [comment]
you're welcome. Closing
