### ISSUE TITLE
Action crashes on a branch with a dash '-'

### ISSUE THREAD

**Issue by giuliov** [GitTools/actions#158]
Extract of build log
```log
2020-07-21T05:39:22.0251472Z Tool 'gitversion.tool' (version '5.2.4') was successfully installed.
2020-07-21T05:39:22.1894396Z ##[group]Run gittools/actions/gitversion/execute@v0.9.2
2020-07-21T05:39:22.1894880Z with:
2020-07-21T05:39:22.1895155Z   useConfigFile: false
2020-07-21T05:39:22.1895456Z   updateAssemblyInfo: false
2020-07-21T05:39:22.1895744Z env:
2020-07-21T05:39:22.1896013Z   DOTNETSDK_VERSION: 3.1.101
2020-07-21T05:39:22.1896298Z   CONFIGURATION: Release
2020-07-21T05:39:22.1896581Z   RUN_INTEGRATION_TESTS: true
2020-07-21T05:39:22.1896878Z   DOTNET_CLI_TELEMETRY_OPTOUT: 1
2020-07-21T05:39:22.1897185Z   DOTNET_ROOT: ../share/dotnet
2020-07-21T05:39:22.1897469Z ##[endgroup]
2020-07-21T05:39:22.2528453Z Command: dotnet-gitversion /home/runner/work/aggregator-cli/aggregator-cli /output json /output buildserver
2020-07-21T05:39:22.2565117Z [command]/opt/hostedtoolcache/GitVersion.Tool/5.2.4/x64/dotnet-gitversion /home/runner/work/aggregator-cli/aggregator-cli /output json /output buildserver
2020-07-21T05:39:22.4760436Z INFO [07/21/20 5:39:22:47] Working directory: /home/runner/work/aggregator-cli/aggregator-cli
2020-07-21T05:39:22.4907582Z INFO [07/21/20 5:39:22:49] Applicable build agent found: 'GitHubActions'.
2020-07-21T05:39:22.4909907Z INFO [07/21/20 5:39:22:49] Branch from build environment: refs/heads/issue-142
2020-07-21T05:39:22.4920479Z INFO [07/21/20 5:39:22:49] Begin: Normalizing git directory for branch 'refs/heads/issue-142'
2020-07-21T05:39:22.5195769Z   INFO [07/21/20 5:39:22:51] One remote found (origin -> 'https://github.com/tfsaggregator/aggregator-cli').
2020-07-21T05:39:22.5222316Z   INFO [07/21/20 5:39:22:52] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
2020-07-21T05:39:22.5260912Z   INFO [07/21/20 5:39:22:52] Creating local branch refs/heads/issue-142
2020-07-21T05:39:22.5484313Z   INFO [07/21/20 5:39:22:54] Creating local branch from remote tracking 'refs/remotes/origin/feature/slots'.
2020-07-21T05:39:22.5597881Z   INFO [07/21/20 5:39:22:55] Creating local branch from remote tracking 'refs/remotes/origin/giuliov/cache-connections'.
2020-07-21T05:39:22.5612375Z   INFO [07/21/20 5:39:22:56] Creating local branch from remote tracking 'refs/remotes/origin/giuliov/oauth'.
2020-07-21T05:39:22.5625795Z   INFO [07/21/20 5:39:22:56] Creating local branch from remote tracking 'refs/remotes/origin/master'.
2020-07-21T05:39:22.5637148Z   INFO [07/21/20 5:39:22:56] HEAD points at branch 'refs/heads/issue-142'.
2020-07-21T05:39:22.5648555Z   INFO [07/21/20 5:39:22:56] End: Normalizing git directory for branch 'refs/heads/issue-142' (Took: 72.19ms)
2020-07-21T05:39:22.5649185Z   INFO [07/21/20 5:39:22:56] Project root is: /home/runner/work/aggregator-cli/aggregator-cli/
2020-07-21T05:39:22.5649791Z   INFO [07/21/20 5:39:22:56] DotGit directory is: /home/runner/work/aggregator-cli/aggregator-cli/.git
2020-07-21T05:39:22.5781513Z   INFO [07/21/20 5:39:22:57] Begin: Loading version variables from disk cache
2020-07-21T05:39:22.5791805Z     INFO [07/21/20 5:39:22:57] Cache file /home/runner/work/aggregator-cli/aggregator-cli/.git/gitversion_cache/3DAAEA6ABF273F5F3A5B71F8C369F76D3CDE340B.yml not found.
2020-07-21T05:39:22.5792278Z   INFO [07/21/20 5:39:22:57] End: Loading version variables from disk cache (Took: 0.92ms)
2020-07-21T05:39:22.5970458Z   INFO [07/21/20 5:39:22:59] Using latest commit on specified branch
2020-07-21T05:39:22.5997194Z   INFO [07/21/20 5:39:22:59] No branch configuration found for branch issue-142, falling back to default configuration
2020-07-21T05:39:22.6044512Z   INFO [07/21/20 5:39:22:60] Begin: Attempting to inherit branch configuration from parent branch
2020-07-21T05:39:22.6098527Z     INFO [07/21/20 5:39:22:60] Begin: Finding branch source of 'issue-142'
2020-07-21T05:39:22.6213963Z       INFO [07/21/20 5:39:22:62] Begin: Finding merge base between 'issue-142' and 'master'.
2020-07-21T05:39:22.6261237Z         INFO [07/21/20 5:39:22:62] Found merge base of 8925d975b18109279de68632fb72ad44712f8e85
2020-07-21T05:39:22.6324560Z         INFO [07/21/20 5:39:22:63] Merge base of issue-142' and 'master is 8925d975b18109279de68632fb72ad44712f8e85
2020-07-21T05:39:22.6325378Z       INFO [07/21/20 5:39:22:63] End: Finding merge base between 'issue-142' and 'master'. (Took: 11.00ms)
2020-07-21T05:39:22.6330481Z       INFO [07/21/20 5:39:22:63] Begin: Finding merge base between 'issue-142' and 'origin/master'.
2020-07-21T05:39:22.6330926Z         INFO [07/21/20 5:39:22:63] Found merge base of 8925d975b18109279de68632fb72ad44712f8e85
2020-07-21T05:39:22.6331580Z         INFO [07/21/20 5:39:22:63] Merge base of issue-142' and 'origin/master is 8925d975b18109279de68632fb72ad44712f8e85
2020-07-21T05:39:22.6332222Z       INFO [07/21/20 5:39:22:63] End: Finding merge base between 'issue-142' and 'origin/master'. (Took: 0.27ms)
2020-07-21T05:39:22.6403235Z       INFO [07/21/20 5:39:22:63] Multiple source branches have been found, picking the first one (master).
2020-07-21T05:39:22.6403647Z This may result in incorrect commit counting.
2020-07-21T05:39:22.6403955Z Options were:
2020-07-21T05:39:22.6404261Z master, origin/master
2020-07-21T05:39:22.6405051Z     INFO [07/21/20 5:39:22:63] End: Finding branch source of 'issue-142' (Took: 30.33ms)
2020-07-21T05:39:22.6437942Z     INFO [07/21/20 5:39:22:64] Begin: Getting branches containing the commit '8925d975b18109279de68632fb72ad44712f8e85'.
2020-07-21T05:39:22.6438386Z       INFO [07/21/20 5:39:22:64] Trying to find direct branches.
2020-07-21T05:39:22.6438772Z       INFO [07/21/20 5:39:22:64] No direct branches found, searching through all branches.
2020-07-21T05:39:22.6439361Z       INFO [07/21/20 5:39:22:64] Searching for commits reachable from 'master'.
2020-07-21T05:39:22.6479864Z       INFO [07/21/20 5:39:22:64] The branch 'master' has a matching commit.
2020-07-21T05:39:22.6480507Z       INFO [07/21/20 5:39:22:64] Searching for commits reachable from 'origin/master'.
2020-07-21T05:39:22.6484781Z       INFO [07/21/20 5:39:22:64] The branch 'origin/master' has a matching commit.
2020-07-21T05:39:22.6485495Z     INFO [07/21/20 5:39:22:64] End: Getting branches containing the commit '8925d975b18109279de68632fb72ad44712f8e85'. (Took: 4.80ms)
2020-07-21T05:39:22.6486356Z     INFO [07/21/20 5:39:22:64] Begin: Getting branches containing the commit '28709864823a546ba114556bff36b8226f93a35a'.
2020-07-21T05:39:22.6486760Z       INFO [07/21/20 5:39:22:64] Trying to find direct branches.
2020-07-21T05:39:22.6487142Z       INFO [07/21/20 5:39:22:64] No direct branches found, searching through all branches.
2020-07-21T05:39:22.6487725Z       INFO [07/21/20 5:39:22:64] Searching for commits reachable from 'master'.
2020-07-21T05:39:22.6513101Z       INFO [07/21/20 5:39:22:65] The branch 'master' has no matching commits.
2020-07-21T05:39:22.6513771Z       INFO [07/21/20 5:39:22:65] Searching for commits reachable from 'origin/master'.
2020-07-21T05:39:22.6585476Z       INFO [07/21/20 5:39:22:65] The branch 'origin/master' has no matching commits.
2020-07-21T05:39:22.6586228Z     INFO [07/21/20 5:39:22:65] End: Getting branches containing the commit '28709864823a546ba114556bff36b8226f93a35a'. (Took: 7.65ms)
2020-07-21T05:39:22.6586655Z     INFO [07/21/20 5:39:22:65] Found possible parent branches: master, origin/master
2020-07-21T05:39:22.6587059Z     WARN [07/21/20 5:39:22:65] Failed to inherit Increment branch configuration, ended up with: master, origin/master
2020-07-21T05:39:22.6587432Z Falling back to master branch config
2020-07-21T05:39:22.6587801Z   INFO [07/21/20 5:39:22:65] End: Attempting to inherit branch configuration from parent branch (Took: 53.27ms)
2020-07-21T05:39:22.6623632Z   INFO [07/21/20 5:39:22:66] Running against branch: issue-142 (28709864823a546ba114556bff36b8226f93a35a)
2020-07-21T05:39:22.6641317Z   INFO [07/21/20 5:39:22:66] Begin: Calculating base versions
2020-07-21T05:39:22.6749978Z     INFO [07/21/20 5:39:22:67] Fallback base version: 0.1.0 with commit count source a1125bc8a77e5a8ac8d1b842ae17ffa85715cc35 (Incremented: None)
2020-07-21T05:39:22.7660931Z     INFO [07/21/20 5:39:22:76] Found commit [28709864823a546ba114556bff36b8226f93a35a] matching merge message format: Default
2020-07-21T05:39:22.7757358Z     INFO [07/21/20 5:39:22:77] Merge message 'Merge branch 'release/0.9.10'': 0.9.10 with commit count source 782b6ff467d699c68b53d0a5b85e03f561f3f09e (Incremented: None)
2020-07-21T05:39:22.8016565Z     INFO [07/21/20 5:39:22:80] Git tag 'v0.9.13': 0.9.13 with commit count source 8925d975b18109279de68632fb72ad44712f8e85 (Incremented: 0.9.14)
2020-07-21T05:39:22.8017527Z     INFO [07/21/20 5:39:22:80] Git tag 'v0.9.12': 0.9.12 with commit count source f89f53e781120a33bf110154554233f025b26c5a (Incremented: 0.9.13)
2020-07-21T05:39:22.8018409Z     INFO [07/21/20 5:39:22:80] Git tag 'v0.9.11': 0.9.11 with commit count source ff46602262e4b1fef7f679947bad6b8103d1e407 (Incremented: 0.9.12)
2020-07-21T05:39:22.8020432Z     INFO [07/21/20 5:39:22:80] Git tag 'v0.9.10': 0.9.10 with commit count source 057718c2397063e540374de64c79c9d9becce80f (Incremented: 0.9.11)
2020-07-21T05:39:22.8021599Z     INFO [07/21/20 5:39:22:80] Git tag 'v0.9.9': 0.9.9 with commit count source 251e71107d297b11756722bc16048b93b6cf50c8 (Incremented: 0.9.10)
2020-07-21T05:39:22.8082855Z     INFO [07/21/20 5:39:22:80] Found multiple base versions which will produce the same SemVer (0.9.14), taking oldest source for commit counting (Git tag 'v0.9.13')
2020-07-21T05:39:22.8088195Z     INFO [07/21/20 5:39:22:80] Base version used: Git tag 'v0.9.13': 0.9.13 with commit count source 8925d975b18109279de68632fb72ad44712f8e85 (Incremented: 0.9.14)
2020-07-21T05:39:22.8100649Z   INFO [07/21/20 5:39:22:80] End: Calculating base versions (Took: 144.24ms)
2020-07-21T05:39:22.8192155Z   INFO [07/21/20 5:39:22:80] 1 commits found between 8925d975b18109279de68632fb72ad44712f8e85 and 28709864823a546ba114556bff36b8226f93a35a
2020-07-21T05:39:22.8192588Z   INFO [07/21/20 5:39:22:80] Using branch name to calculate version tag
2020-07-21T05:39:22.8195230Z   INFO [07/21/20 5:39:22:81] Begin: Getting version tags from branch 'refs/heads/issue-142'.
2020-07-21T05:39:22.8196421Z   INFO [07/21/20 5:39:22:81] End: Getting version tags from branch 'refs/heads/issue-142'. (Took: 8.30ms)
2020-07-21T05:39:22.8283273Z   INFO [07/21/20 5:39:22:82] Begin: Creating dictionary
2020-07-21T05:39:22.8309421Z   INFO [07/21/20 5:39:22:83] End: Creating dictionary (Took: 5.15ms)
2020-07-21T05:39:22.8344693Z   INFO [07/21/20 5:39:22:83] Begin: Storing version variables to cache file /home/runner/work/aggregator-cli/aggregator-cli/.git/gitversion_cache/3DAAEA6ABF273F5F3A5B71F8C369F76D3CDE340B.yml
2020-07-21T05:39:22.8906092Z   INFO [07/21/20 5:39:22:89] End: Storing version variables to cache file /home/runner/work/aggregator-cli/aggregator-cli/.git/gitversion_cache/3DAAEA6ABF273F5F3A5B71F8C369F76D3CDE340B.yml (Took: 55.92ms)
2020-07-21T05:39:22.8914373Z   INFO [07/21/20 5:39:22:89] Running on Unix.
2020-07-21T05:39:22.8915227Z   INFO [07/21/20 5:39:22:89] Applicable build agent found: 'GitHubActions'.
2020-07-21T05:39:22.8919531Z Executing GenerateSetVersionMessage for 'GitHubActions'.
2020-07-21T05:39:22.8919787Z 
2020-07-21T05:39:22.8920426Z Executing GenerateBuildLogOutput for 'GitHubActions'.
2020-07-21T05:39:22.8978205Z ***
2020-07-21T05:39:22.8978493Z   "Major":0,
2020-07-21T05:39:22.8978767Z   "Minor":9,
2020-07-21T05:39:22.8979033Z   "Patch":14,
2020-07-21T05:39:22.8979503Z   "PreReleaseTag":"issue-142.1",
2020-07-21T05:39:22.8979980Z   "PreReleaseTagWithDash":"-issue-142.1",
2020-07-21T05:39:22.8980432Z   "PreReleaseLabel":"issue-142",
2020-07-21T05:39:22.8980731Z   "PreReleaseNumber":1,
2020-07-21T05:39:22.8981023Z   "WeightedPreReleaseNumber":1,
2020-07-21T05:39:22.8981311Z   "BuildMetaData":1,
2020-07-21T05:39:22.8981606Z   "BuildMetaDataPadded":"0001",
2020-07-21T05:39:22.8982154Z   "FullBuildMetaData":"1.Branch.issue-142.Sha.28709864823a546ba114556bff36b8226f93a35a",
2020-07-21T05:39:22.8982502Z   "MajorMinorPatch":"0.9.14",
2020-07-21T05:39:22.8982937Z   "SemVer":"0.9.14-issue-142.1",
2020-07-21T05:39:22.8983389Z   "LegacySemVer":"0.9.14-issue-142-1",
2020-07-21T05:39:22.8984164Z   "LegacySemVerPadded":"0.9.14-issue-142-0001",
2020-07-21T05:39:22.8984595Z   "AssemblySemVer":"0.9.14.0",
2020-07-21T05:39:22.8984894Z   "AssemblySemFileVer":"0.9.14.0",
2020-07-21T05:39:22.8985360Z   "FullSemVer":"0.9.14-issue-142.1+1",
2020-07-21T05:39:22.8985955Z   "InformationalVersion":"0.9.14-issue-142.1+1.Branch.issue-142.Sha.28709864823a546ba114556bff36b8226f93a35a",
2020-07-21T05:39:22.8986447Z   "BranchName":"issue-142",
2020-07-21T05:39:22.8986888Z   "EscapedBranchName":"issue-142",
2020-07-21T05:39:22.8987209Z   "Sha":"28709864823a546ba114556bff36b8226f93a35a",
2020-07-21T05:39:22.8987522Z   "ShortSha":2870986,
2020-07-21T05:39:22.8987968Z   "NuGetVersionV2":"0.9.14-issue-142-0001",
2020-07-21T05:39:22.8988432Z   "NuGetVersion":"0.9.14-issue-142-0001",
2020-07-21T05:39:22.8988906Z   "NuGetPreReleaseTagV2":"issue-142-0001",
2020-07-21T05:39:22.8989363Z   "NuGetPreReleaseTag":"issue-142-0001",
2020-07-21T05:39:22.8989708Z   "VersionSourceSha":"8925d975b18109279de68632fb72ad44712f8e85",
2020-07-21T05:39:22.8990069Z   "CommitsSinceVersionSource":1,
2020-07-21T05:39:22.8990393Z   "CommitsSinceVersionSourcePadded":"0001",
2020-07-21T05:39:22.8990849Z   "CommitDate":"2020-07-20"
2020-07-21T05:39:22.8991364Z ***
2020-07-21T05:39:22.9225334Z (node:2982) UnhandledPromiseRejectionWarning: TypeError: (e || "").replace is not a function
2020-07-21T05:39:22.9225791Z     at /home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:943
2020-07-21T05:39:22.9226199Z     at s.toString (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:1005)
2020-07-21T05:39:22.9226607Z     at o (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:372)
2020-07-21T05:39:22.9227017Z     at Object.t.issue (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:5:432)
2020-07-21T05:39:22.9227432Z     at c (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:9:741)
2020-07-21T05:39:22.9227960Z     at Object.t.setFailed (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:9:1482)
2020-07-21T05:39:22.9228390Z     at h.setFailed (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:308:1902)
2020-07-21T05:39:22.9228806Z     at Object.<anonymous> (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:336:1575)
2020-07-21T05:39:22.9229179Z     at Generator.next (<anonymous>)
2020-07-21T05:39:22.9229544Z     at s (/home/runner/work/_actions/gittools/actions/v0.9.2/dist/github/gitversion/execute/bundle.js:336:170)
2020-07-21T05:39:22.9230013Z (node:2982) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-07-21T05:39:22.9230875Z (node:2982) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-07-21T05:39:22.9319133Z ##[group]Run rm $GITHUB_WORKSPACE/src/integrationtests-cli/logon-data.json
2020-07-21T05:39:22.9319546Z [36;1mrm $GITHUB_WORKSPACE/src/integrationtests-cli/logon-data.json[0m
2020-07-21T05:39:22.9359816Z shell: /bin/bash -e ***0***
2020-07-21T05:39:22.9360113Z env:
2020-07-21T05:39:22.9360408Z   DOTNETSDK_VERSION: 3.1.101
2020-07-21T05:39:22.9360696Z   CONFIGURATION: Release
2020-07-21T05:39:22.9360978Z   RUN_INTEGRATION_TESTS: true
2020-07-21T05:39:22.9361268Z   DOTNET_CLI_TELEMETRY_OPTOUT: 1
2020-07-21T05:39:22.9361565Z   DOTNET_ROOT: ../share/dotnet
2020-07-21T05:39:22.9361858Z   GitVersion_Major: 0
2020-07-21T05:39:22.9362157Z   GitVersion_Minor: 9
2020-07-21T05:39:22.9362434Z   GitVersion_Patch: 14
2020-07-21T05:39:22.9362723Z   GitVersion_PreReleaseTag: issue-142.1
2020-07-21T05:39:22.9363040Z   GitVersion_PreReleaseTagWithDash: -issue-142.1
2020-07-21T05:39:22.9363541Z   GitVersion_PreReleaseLabel: issue-142
2020-07-21T05:39:22.9363867Z   GitVersion_PreReleaseNumber: 1
2020-07-21T05:39:22.9364221Z   GitVersion_WeightedPreReleaseNumber: 1
2020-07-21T05:39:22.9364528Z   GitVersion_BuildMetaData: 1
2020-07-21T05:39:22.9364840Z   GitVersion_BuildMetaDataPadded: 0001
2020-07-21T05:39:22.9365201Z   GitVersion_FullBuildMetaData: 1.Branch.issue-142.Sha.28709864823a546ba114556bff36b8226f93a35a
2020-07-21T05:39:22.9365544Z   GitVersion_MajorMinorPatch: 0.9.14
2020-07-21T05:39:22.9365852Z   GitVersion_SemVer: 0.9.14-issue-142.1
2020-07-21T05:39:22.9366466Z   GitVersion_LegacySemVer: 0.9.14-issue-142-1
2020-07-21T05:39:22.9366833Z   GitVersion_LegacySemVerPadded: 0.9.14-issue-142-0001
2020-07-21T05:39:22.9367153Z   GitVersion_AssemblySemVer: 0.9.14.0
2020-07-21T05:39:22.9367462Z   GitVersion_AssemblySemFileVer: 0.9.14.0
2020-07-21T05:39:22.9367778Z   GitVersion_FullSemVer: 0.9.14-issue-142.1+1
2020-07-21T05:39:22.9368162Z   GitVersion_InformationalVersion: 0.9.14-issue-142.1+1.Branch.issue-142.Sha.28709864823a546ba114556bff36b8226f93a35a
2020-07-21T05:39:22.9368513Z   GitVersion_BranchName: issue-142
2020-07-21T05:39:22.9368811Z   GitVersion_EscapedBranchName: issue-142
2020-07-21T05:39:22.9369133Z   GitVersion_Sha: 28709864823a546ba114556bff36b8226f93a35a
2020-07-21T05:39:22.9369443Z   GitVersion_ShortSha: 2870986
2020-07-21T05:39:22.9369761Z   GitVersion_NuGetVersionV2: 0.9.14-issue-142-0001
2020-07-21T05:39:22.9370088Z   GitVersion_NuGetVersion: 0.9.14-issue-142-0001
2020-07-21T05:39:22.9370411Z   GitVersion_NuGetPreReleaseTagV2: issue-142-0001
2020-07-21T05:39:22.9370735Z   GitVersion_NuGetPreReleaseTag: issue-142-0001
2020-07-21T05:39:22.9371083Z   GitVersion_VersionSourceSha: 8925d975b18109279de68632fb72ad44712f8e85
2020-07-21T05:39:22.9371424Z   GitVersion_CommitsSinceVersionSource: 1
2020-07-21T05:39:22.9371740Z   GitVersion_CommitsSinceVersionSourcePadded: 0001
2020-07-21T05:39:22.9372048Z   GitVersion_CommitDate: 2020-07-20
2020-07-21T05:39:22.9372345Z ##[endgroup]
```
Renaming the branch from `issue-142` to `issue_142` fixed.

**Comment by CallumBradburyBJSS** [comment]
Having the same issue

**Comment by asbjornu** [comment]
Seems like a duplicate of #76. Have you tried version 0.9.4 of the action?

**Comment by asbjornu** [comment]
Can you also try with a newer version of GitVersion? The latest as of now is `5.3.7`.
