### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by cneuwirt** [GitTools/actions#439]
I have a version simple azure-pipelines.yml with the following steps

steps:
  - task: gitversion/setup@0
    displayName: Install GitVersion
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    displayName: Determine Version
    inputs:
      useConfigFile: true
      configFilePath: 'GitVersion.yml'

This is resulting in the following failure on the build agent

2021-06-07T11:57:25.2470653Z ##[section]Starting: Determine Version
2021-06-07T11:57:25.2480530Z ==============================================================================
2021-06-07T11:57:25.2480879Z Task         : Execute GitVersion Task
2021-06-07T11:57:25.2481227Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2021-06-07T11:57:25.2481547Z Version      : 0.9.9
2021-06-07T11:57:25.2481782Z Author       : GitTools Contributors
2021-06-07T11:57:25.2482122Z Help         : See the [documentation](https://gitversion.net/docs/) for help
2021-06-07T11:57:25.2482495Z ==============================================================================
2021-06-07T11:57:25.4638032Z Command: dotnet-gitversion /home/vsts/work/1/s /output json /output buildserver /config /home/vsts/work/1/s/GitVersion.yml
2021-06-07T11:57:25.4656900Z [command]/opt/hostedtoolcache/GitVersion.Tool/5.6.10/x64/dotnet-gitversion /home/vsts/work/1/s /output json /output buildserver /config /home/vsts/work/1/s/GitVersion.yml
2021-06-07T11:57:26.0299549Z INFO [06/07/21 11:57:25:68] Working directory: /home/vsts/work/1/s
2021-06-07T11:57:26.0301444Z INFO [06/07/21 11:57:25:71] Branch from build environment: refs/heads/feature/initial
2021-06-07T11:57:26.0302498Z INFO [06/07/21 11:57:25:71] Project root is: /home/vsts/work/1/s/
2021-06-07T11:57:26.0303571Z INFO [06/07/21 11:57:25:71] DotGit directory is: /home/vsts/work/1/s/.git
2021-06-07T11:57:26.0318970Z   ERROR [06/07/21 11:57:25:98] An unexpected error occurred:
2021-06-07T11:57:26.0320111Z System.NullReferenceException: Object reference not set to an instance of an object.
2021-06-07T11:57:26.0320895Z    at GitVersion.GitObject..ctor(GitObject innerGitObject) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitObject.cs:line 12
2021-06-07T11:57:26.0323212Z    at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
2021-06-07T11:57:26.0324326Z    at GitVersion.GitRepository.<>c__DisplayClass27_0.<FindMergeBase>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 60
2021-06-07T11:57:26.0325316Z    at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
2021-06-07T11:57:26.0330969Z    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
2021-06-07T11:57:26.0332104Z    at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
2021-06-07T11:57:26.0332739Z    at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
2021-06-07T11:57:26.0333313Z    at Polly.Policy`1.Execute(Func`1 action)
2021-06-07T11:57:26.0334234Z    at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 42
2021-06-07T11:57:26.0335296Z    at GitVersion.GitRepository.FindMergeBase(ICommit commit, ICommit otherCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 58
2021-06-07T11:57:26.0336254Z    at GitVersion.RepositoryStore.FindMergeBase(IBranch branch, IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 46
2021-06-07T11:57:26.0337297Z    at GitVersion.RepositoryStore.<>c__DisplayClass29_0.<GetMergeCommitsForBranch>b__2(IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 466
2021-06-07T11:57:26.0338063Z    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2021-06-07T11:57:26.0338607Z    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
2021-06-07T11:57:26.0339046Z    at System.Linq.OrderedEnumerable`1.ToList()
2021-06-07T11:57:26.0339758Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2021-06-07T11:57:26.0340775Z    at GitVersion.RepositoryStore.GetMergeCommitsForBranch(IBranch branch, Config configuration, IEnumerable`1 excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 450
2021-06-07T11:57:26.0341887Z    at GitVersion.RepositoryStore.FindCommitBranchWasBranchedFrom(IBranch branch, Config configuration, IBranch[] excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 328
2021-06-07T11:57:26.0343182Z    at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 81
2021-06-07T11:57:26.0344735Z    at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 47
2021-06-07T11:57:26.0346043Z    at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 40
2021-06-07T11:57:26.0346922Z    at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 38
2021-06-07T11:57:26.0347588Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2021-06-07T11:57:26.0348034Z    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2021-06-07T11:57:26.0348505Z    at System.Lazy`1.CreateValue()
2021-06-07T11:57:26.0348796Z    at System.Lazy`1.get_Value()
2021-06-07T11:57:26.0349435Z    at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 17
2021-06-07T11:57:26.0350509Z    at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 32
2021-06-07T11:57:26.0351417Z    at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
2021-06-07T11:57:26.0352324Z    at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70
2021-06-07T11:57:26.0362498Z INFO [06/07/21 11:57:25:71] Begin: Normalizing git directory for branch 'refs/heads/feature/initial'
2021-06-07T11:57:26.0363889Z   INFO [06/07/21 11:57:25:74] One remote found (origin -> 'https://Venatrust@dev.azure.com/Venatrust/Vespy/_git/venatrust-chassis').
2021-06-07T11:57:26.0365008Z   INFO [06/07/21 11:57:25:75] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
2021-06-07T11:57:26.0365602Z   INFO [06/07/21 11:57:25:75] Creating local branch feature/initial
2021-06-07T11:57:26.0366521Z   INFO [06/07/21 11:57:25:79] Creating local branch from remote tracking 'refs/remotes/origin/a26bb8abb3f3eec6db01a365ea8368a006a258be'.
2021-06-07T11:57:26.0367327Z   INFO [06/07/21 11:57:25:80] Creating local branch from remote tracking 'refs/remotes/origin/main'.
2021-06-07T11:57:26.0368180Z   INFO [06/07/21 11:57:25:80] Creating local branch from remote tracking 'refs/remotes/origin/master'.
2021-06-07T11:57:26.0368877Z   INFO [06/07/21 11:57:25:80] HEAD points at branch 'refs/heads/feature/initial'.
2021-06-07T11:57:26.0369711Z   INFO [06/07/21 11:57:25:80] End: Normalizing git directory for branch 'refs/heads/feature/initial' (Took: 94.19ms)
2021-06-07T11:57:26.0370255Z   INFO [06/07/21 11:57:25:82] Begin: Loading version variables from disk cache
2021-06-07T11:57:26.0370972Z     INFO [06/07/21 11:57:25:82] Cache file /home/vsts/work/1/s/.git/gitversion_cache/1B4546E6C09EB2D4F6627BC3EDCFF9B9E595DF73.yml not found.
2021-06-07T11:57:26.0371567Z   INFO [06/07/21 11:57:25:82] End: Loading version variables from disk cache (Took: 0.88ms)
2021-06-07T11:57:26.0372990Z   INFO [06/07/21 11:57:25:93] Using latest commit on specified branch
2021-06-07T11:57:26.0373538Z   INFO [06/07/21 11:57:25:94] Begin: Attempting to inherit branch configuration from parent branch
2021-06-07T11:57:26.0374265Z     INFO [06/07/21 11:57:25:94] Begin: Finding branch source of 'feature/initial'
2021-06-07T11:57:26.0375046Z       INFO [06/07/21 11:57:25:95] Begin: Finding merge base between 'feature/initial' and 'main'.
2021-06-07T11:57:26.0375837Z       INFO [06/07/21 11:57:25:96] End: Finding merge base between 'feature/initial' and 'main'. (Took: 10.53ms)
2021-06-07T11:57:26.0376679Z     INFO [06/07/21 11:57:25:96] End: Finding branch source of 'feature/initial' (Took: 20.64ms)
2021-06-07T11:57:26.0377286Z   INFO [06/07/21 11:57:25:96] End: Attempting to inherit branch configuration from parent branch (Took: 26.09ms)
2021-06-07T11:57:26.0377959Z   INFO [06/07/21 11:57:25:98] Attempting to show the current git graph (please include in issue): 
2021-06-07T11:57:26.0378442Z   INFO [06/07/21 11:57:25:98] Showing max of 100 commits
2021-06-07T11:57:26.0379391Z   INFO [06/07/21 11:57:26:00] * a26bb8a 22 seconds ago  (HEAD -> feature/initial, origin/feature/initial, origin/a26bb8abb3f3eec6db01a365ea8368a006a258be, a26bb8abb3f3eec6db01a365ea8368a006a258be)
2021-06-07T11:57:26.0379998Z * 27fb43b 2 minutes ago 
2021-06-07T11:57:26.0380263Z * fa73742 7 minutes ago 
2021-06-07T11:57:26.0380585Z * 91a2964 19 minutes ago 
2021-06-07T11:57:26.0380853Z * a1621a4 21 minutes ago 
2021-06-07T11:57:26.0381225Z * 9df0354 27 minutes ago 
2021-06-07T11:57:26.0381499Z * b5feb07 28 minutes ago 
2021-06-07T11:57:26.0381776Z * 33f07cc 42 minutes ago 
2021-06-07T11:57:26.0382093Z * a87e0d3 3 days ago 
2021-06-07T11:57:26.0382358Z * 99bb9a4 4 days ago 
2021-06-07T11:57:26.0382614Z * 69d9496 4 days ago 
2021-06-07T11:57:26.0382929Z * d0dba47 5 days ago 
2021-06-07T11:57:26.0383423Z * 7ff6f66 5 days ago 
2021-06-07T11:57:26.0383843Z * 1dd8077 7 days ago 
2021-06-07T11:57:26.0384138Z * 5306417 7 days ago  (origin/master, master)
2021-06-07T11:57:26.0384433Z * e38f00a 8 days ago 
2021-06-07T11:57:26.0384748Z * 6c6f11c 8 days ago 
2021-06-07T11:57:26.0385008Z * a47e70e 12 days ago 
2021-06-07T11:57:26.0385370Z * 7a1a647 8 days ago  (origin/main, main)
2021-06-07T11:57:26.0385534Z 
2021-06-07T11:57:26.0386104Z INFO [06/07/21 11:57:25:65] Applicable build agent found: 'AzurePipelines'.
2021-06-07T11:57:26.0386632Z INFO [06/07/21 11:57:25:68] Working directory: /home/vsts/work/1/s
2021-06-07T11:57:26.0387103Z INFO [06/07/21 11:57:25:71] Branch from build environment: refs/heads/feature/initial
2021-06-07T11:57:26.0387570Z INFO [06/07/21 11:57:25:71] Project root is: /home/vsts/work/1/s/
2021-06-07T11:57:26.0388187Z INFO [06/07/21 11:57:25:71] DotGit directory is: /home/vsts/work/1/s/.git
2021-06-07T11:57:26.0388917Z INFO [06/07/21 11:57:25:71] Begin: Normalizing git directory for branch 'refs/heads/feature/initial'
2021-06-07T11:57:26.0389887Z   INFO [06/07/21 11:57:25:74] One remote found (origin -> 'https://Venatrust@dev.azure.com/Venatrust/Vespy/_git/venatrust-chassis').
2021-06-07T11:57:26.0390583Z   INFO [06/07/21 11:57:25:75] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
2021-06-07T11:57:26.0391208Z   INFO [06/07/21 11:57:25:75] Creating local branch feature/initial
2021-06-07T11:57:26.0391998Z   INFO [06/07/21 11:57:25:79] Creating local branch from remote tracking 'refs/remotes/origin/a26bb8abb3f3eec6db01a365ea8368a006a258be'.
2021-06-07T11:57:26.0392850Z   INFO [06/07/21 11:57:25:80] Creating local branch from remote tracking 'refs/remotes/origin/main'.
2021-06-07T11:57:26.0394531Z   INFO [06/07/21 11:57:25:80] Creating local branch from remote tracking 'refs/remotes/origin/master'.
2021-06-07T11:57:26.0395472Z   INFO [06/07/21 11:57:25:80] HEAD points at branch 'refs/heads/feature/initial'.
2021-06-07T11:57:26.0396314Z   INFO [06/07/21 11:57:25:80] End: Normalizing git directory for branch 'refs/heads/feature/initial' (Took: 94.19ms)
2021-06-07T11:57:26.0396847Z   INFO [06/07/21 11:57:25:82] Begin: Loading version variables from disk cache
2021-06-07T11:57:26.0397461Z     INFO [06/07/21 11:57:25:82] Cache file /home/vsts/work/1/s/.git/gitversion_cache/1B4546E6C09EB2D4F6627BC3EDCFF9B9E595DF73.yml not found.
2021-06-07T11:57:26.0398057Z   INFO [06/07/21 11:57:25:82] End: Loading version variables from disk cache (Took: 0.88ms)
2021-06-07T11:57:26.0398600Z   INFO [06/07/21 11:57:25:93] Using latest commit on specified branch
2021-06-07T11:57:26.0399069Z   INFO [06/07/21 11:57:25:94] Begin: Attempting to inherit branch configuration from parent branch
2021-06-07T11:57:26.0399833Z     INFO [06/07/21 11:57:25:94] Begin: Finding branch source of 'feature/initial'
2021-06-07T11:57:26.0400559Z       INFO [06/07/21 11:57:25:95] Begin: Finding merge base between 'feature/initial' and 'main'.
2021-06-07T11:57:26.0401408Z       INFO [06/07/21 11:57:25:96] End: Finding merge base between 'feature/initial' and 'main'. (Took: 10.53ms)
2021-06-07T11:57:26.0403329Z     INFO [06/07/21 11:57:25:96] End: Finding branch source of 'feature/initial' (Took: 20.64ms)
2021-06-07T11:57:26.0403941Z   INFO [06/07/21 11:57:25:96] End: Attempting to inherit branch configuration from parent branch (Took: 26.09ms)
2021-06-07T11:57:26.0404577Z   ERROR [06/07/21 11:57:25:98] An unexpected error occurred:
2021-06-07T11:57:26.0405036Z System.NullReferenceException: Object reference not set to an instance of an object.
2021-06-07T11:57:26.0405864Z    at GitVersion.GitObject..ctor(GitObject innerGitObject) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitObject.cs:line 12
2021-06-07T11:57:26.0406624Z    at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
2021-06-07T11:57:26.0407475Z    at GitVersion.GitRepository.<>c__DisplayClass27_0.<FindMergeBase>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 60
2021-06-07T11:57:26.0408135Z    at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
2021-06-07T11:57:26.0409055Z    at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
2021-06-07T11:57:26.0409943Z    at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
2021-06-07T11:57:26.0410524Z    at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
2021-06-07T11:57:26.0411054Z    at Polly.Policy`1.Execute(Func`1 action)
2021-06-07T11:57:26.0411663Z    at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 42
2021-06-07T11:57:26.0412492Z    at GitVersion.GitRepository.FindMergeBase(ICommit commit, ICommit otherCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 58
2021-06-07T11:57:26.0413419Z    at GitVersion.RepositoryStore.FindMergeBase(IBranch branch, IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 46
2021-06-07T11:57:26.0414321Z    at GitVersion.RepositoryStore.<>c__DisplayClass29_0.<GetMergeCommitsForBranch>b__2(IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 466
2021-06-07T11:57:26.0415063Z    at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
2021-06-07T11:57:26.0415477Z    at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
2021-06-07T11:57:26.0415990Z    at System.Linq.OrderedEnumerable`1.ToList()
2021-06-07T11:57:26.0416352Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2021-06-07T11:57:26.0417136Z    at GitVersion.RepositoryStore.GetMergeCommitsForBranch(IBranch branch, Config configuration, IEnumerable`1 excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 450
2021-06-07T11:57:26.0418187Z    at GitVersion.RepositoryStore.FindCommitBranchWasBranchedFrom(IBranch branch, Config configuration, IBranch[] excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 328
2021-06-07T11:57:26.0419528Z    at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 81
2021-06-07T11:57:26.0421077Z    at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 47
2021-06-07T11:57:26.0422213Z    at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 40
2021-06-07T11:57:26.0423637Z    at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 38
2021-06-07T11:57:26.0424318Z    at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
2021-06-07T11:57:26.0424841Z    at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
2021-06-07T11:57:26.0425268Z    at System.Lazy`1.CreateValue()
2021-06-07T11:57:26.0425967Z    at System.Lazy`1.get_Value()
2021-06-07T11:57:26.0433780Z    at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 17
2021-06-07T11:57:26.0434854Z    at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 32
2021-06-07T11:57:26.0435880Z    at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
2021-06-07T11:57:26.0436736Z    at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70
2021-06-07T11:57:26.0437533Z   INFO [06/07/21 11:57:25:98] Attempting to show the current git graph (please include in issue): 
2021-06-07T11:57:26.0438196Z   INFO [06/07/21 11:57:25:98] Showing max of 100 commits
2021-06-07T11:57:26.0439447Z   INFO [06/07/21 11:57:26:00] * a26bb8a 22 seconds ago  (HEAD -> feature/initial, origin/feature/initial, origin/a26bb8abb3f3eec6db01a365ea8368a006a258be, a26bb8abb3f3eec6db01a365ea8368a006a258be)
2021-06-07T11:57:26.0440001Z * 27fb43b 2 minutes ago 
2021-06-07T11:57:26.0440336Z * fa73742 7 minutes ago 
2021-06-07T11:57:26.0440604Z * 91a2964 19 minutes ago 
2021-06-07T11:57:26.0440925Z * a1621a4 21 minutes ago 
2021-06-07T11:57:26.0441196Z * 9df0354 27 minutes ago 
2021-06-07T11:57:26.0441462Z * b5feb07 28 minutes ago 
2021-06-07T11:57:26.0441787Z * 33f07cc 42 minutes ago 
2021-06-07T11:57:26.0442051Z * a87e0d3 3 days ago 
2021-06-07T11:57:26.0442381Z * 99bb9a4 4 days ago 
2021-06-07T11:57:26.0442640Z * 69d9496 4 days ago 
2021-06-07T11:57:26.0442895Z * d0dba47 5 days ago 
2021-06-07T11:57:26.0443207Z * 7ff6f66 5 days ago 
2021-06-07T11:57:26.0443478Z * 1dd8077 7 days ago 
2021-06-07T11:57:26.0443771Z * 5306417 7 days ago  (origin/master, master)
2021-06-07T11:57:26.0444247Z * e38f00a 8 days ago 
2021-06-07T11:57:26.0444504Z * 6c6f11c 8 days ago 
2021-06-07T11:57:26.0444826Z * a47e70e 12 days ago 
2021-06-07T11:57:26.0445116Z * 7a1a647 8 days ago  (origin/main, main)
2021-06-07T11:57:26.0445278Z 
2021-06-07T11:57:26.0445605Z   INFO [06/07/21 11:57:26:01] Done writing 
2021-06-07T11:57:26.0476441Z ##[error]SyntaxError: Unexpected end of JSON input
2021-06-07T11:57:26.0492050Z ##[section]Finishing: Determine Version

Of course, I can run gitversion locally

**Comment by ENikS** [comment]
I think these are the [same issue](https://github.com/GitTools/GitVersion/issues/2734)
