### ISSUE TITLE
Azure Execute hangs for ~25 minutes and then fails with generic node error.

### ISSUE THREAD

**Issue by scphantm** [GitTools/actions#511]
We have a pretty basic pipeline.  

```
  - task: Bash@3
    displayName: Master Branch Normalize
    inputs:
      targetType: 'inline'
      script: |
        cd ${{ parameters.LocalCheckedOutPath }}
        git checkout master
        git checkout main
        git checkout $(Build.SourceBranchName)

  - task: CopyFiles@2
    displayName: Copy in default version and release notes files
    inputs:
      sourceFolder: $(Build.Repository.LocalPath)/PipelineTemplates/CICDTemplates/buildTemplates/default_files
      targetFolder: ${{ parameters.LocalCheckedOutPath }}
      overWrite: false

  - task: gitversion/setup@0
    displayName: GitVersion Setup
    inputs:
      versionSpec: '5.7.x'

  - task: gitversion/execute@0
    displayName: GitVersion Execute
    inputs:
      targetPath: ${{ parameters.LocalCheckedOutPath }}
```

on some repositories, this works fine.  We normalize the master branch locally to solve some sporadic issues, copy in our default `GitVersion.yml` file and then runs gitversion.

What happens on some repos is it will hang for 25ish minutes then fail with a generic Node error.

```
2021-08-26T20:36:30.3937688Z ##[debug]Evaluating condition for step: 'GitVersion Execute'
2021-08-26T20:36:30.3940714Z ##[debug]Evaluating: SucceededNode()
2021-08-26T20:36:30.3941855Z ##[debug]Evaluating SucceededNode:
2021-08-26T20:36:30.3943952Z ##[debug]=> True
2021-08-26T20:36:30.3945137Z ##[debug]Result: True
2021-08-26T20:36:30.3946211Z ##[section]Starting: GitVersion Execute
2021-08-26T20:36:30.3957763Z ==============================================================================
2021-08-26T20:36:30.3958444Z Task         : Execute GitVersion Task
2021-08-26T20:36:30.3959198Z Description  : Easy Semantic Versioning (http://semver.org) for projects using Git
2021-08-26T20:36:30.3959855Z Version      : 0.9.10
2021-08-26T20:36:30.3960349Z Author       : GitTools Contributors
2021-08-26T20:36:30.3961081Z Help         : See the [documentation](https://gitversion.net/docs/) for help
2021-08-26T20:36:30.3961869Z ==============================================================================
2021-08-26T20:36:30.4030018Z ##[debug]Using node path: /agent/externals/node/bin/node
2021-08-26T20:36:30.6242793Z ##[debug]agent.TempDirectory=/agent/_work/_temp
2021-08-26T20:36:30.6264871Z ##[debug]loading inputs and endpoints
2021-08-26T20:36:30.6267804Z ##[debug]loading INPUT_TARGETPATH
2021-08-26T20:36:30.6282164Z ##[debug]loading INPUT_USECONFIGFILE
2021-08-26T20:36:30.6284907Z ##[debug]loading INPUT_CONFIGFILEPATH
2021-08-26T20:36:30.6286569Z ##[debug]loading INPUT_UPDATEASSEMBLYINFO
2021-08-26T20:36:30.6288146Z ##[debug]loading ENDPOINT_AUTH_SYSTEMVSSCONNECTION
2021-08-26T20:36:30.6289713Z ##[debug]loading ENDPOINT_AUTH_SCHEME_SYSTEMVSSCONNECTION
2021-08-26T20:36:30.6291160Z ##[debug]loading ENDPOINT_AUTH_PARAMETER_SYSTEMVSSCONNECTION_ACCESSTOKEN
2021-08-26T20:36:30.6309344Z ##[debug]loading SECRET_SYSTEM_ACCESSTOKEN
2021-08-26T20:36:30.6314967Z ##[debug]loaded 8
2021-08-26T20:36:30.6332033Z ##[debug]Agent.ProxyUrl=undefined
2021-08-26T20:36:30.6339769Z ##[debug]Agent.CAInfo=undefined
2021-08-26T20:36:30.6340871Z ##[debug]Agent.ClientCert=undefined
2021-08-26T20:36:30.6342014Z ##[debug]Agent.SkipCertValidation=undefined
2021-08-26T20:36:30.6354196Z ##[debug]Agent.ProxyUrl=undefined
2021-08-26T20:36:30.6359468Z ##[debug]Agent.CAInfo=undefined
2021-08-26T20:36:30.6360634Z ##[debug]Agent.ClientCert=undefined
2021-08-26T20:36:30.6362736Z ##[debug]check path : /agent/_work/_tasks/gitversion/execute_9013cf7f-ee8d-49f4-a39b-db244928d391/0.9.10/lib.json
2021-08-26T20:36:30.6364692Z ##[debug]adding resource file: /agent/_work/_tasks/gitversion/execute_9013cf7f-ee8d-49f4-a39b-db244928d391/0.9.10/lib.json
2021-08-26T20:36:30.6366316Z ##[debug]system.culture=en-US
2021-08-26T20:36:30.6441160Z ##[debug]Agent.ProxyUrl=undefined
2021-08-26T20:36:30.6442259Z ##[debug]Agent.CAInfo=undefined
2021-08-26T20:36:30.6443310Z ##[debug]Agent.ClientCert=undefined
2021-08-26T20:36:30.6444389Z ##[debug]Agent.SkipCertValidation=undefined
2021-08-26T20:36:30.6459680Z ##[debug]set DOTNET_CLI_TELEMETRY_OPTOUT=true
2021-08-26T20:36:30.6466636Z ##[debug]Processed: ##vso[task.setvariable variable=DOTNET_CLI_TELEMETRY_OPTOUT;isOutput=false;issecret=false;]true
2021-08-26T20:36:30.6468168Z ##[debug]set DOTNET_NOLOGO=true
2021-08-26T20:36:30.6471878Z ##[debug]Processed: ##vso[task.setvariable variable=DOTNET_NOLOGO;isOutput=false;issecret=false;]true
2021-08-26T20:36:30.6473350Z ##[debug]targetPath=/agent/_work/4/s/Myapp
2021-08-26T20:36:30.6483217Z ##[debug]useConfigFile=false
2021-08-26T20:36:30.6486219Z ##[debug]configFilePath=/agent/_work/4/s
2021-08-26T20:36:30.6487286Z ##[debug]updateAssemblyInfo=false
2021-08-26T20:36:30.6488377Z ##[debug]updateAssemblyInfoFilename=undefined
2021-08-26T20:36:30.6489501Z ##[debug]additionalArguments=undefined
2021-08-26T20:36:30.6490670Z ##[debug]Build.SourcesDirectory=/agent/_work/4/s
2021-08-26T20:36:30.6491849Z ##[debug]Build.SourcesDirectory=/agent/_work/4/s
2021-08-26T20:36:30.6508651Z Command: dotnet-gitversion /agent/_work/4/s/Myapp /output json /output buildserver
2021-08-26T20:36:30.6525647Z ##[debug]which 'dotnet-gitversion'
2021-08-26T20:36:30.6535463Z ##[debug]found: '/agent/_work/_tool/GitVersion.Tool/5.7.0/x64/dotnet-gitversion'
2021-08-26T20:36:30.6542346Z ##[debug]/agent/_work/_tool/GitVersion.Tool/5.7.0/x64/dotnet-gitversion arg: ["/agent/_work/4/s/Myapp","/output","json","/output","buildserver"]
2021-08-26T20:36:30.6544773Z ##[debug]exec tool: /agent/_work/_tool/GitVersion.Tool/5.7.0/x64/dotnet-gitversion
2021-08-26T20:36:30.6546073Z ##[debug]arguments:
2021-08-26T20:36:30.6547150Z ##[debug]   /agent/_work/4/s/Myapp
2021-08-26T20:36:30.6548130Z ##[debug]   /output
2021-08-26T20:36:30.6551002Z ##[debug]   json
2021-08-26T20:36:30.6551983Z ##[debug]   /output
2021-08-26T20:36:30.6552973Z ##[debug]   buildserver
2021-08-26T20:36:30.6554910Z [command]/agent/_work/_tool/GitVersion.Tool/5.7.0/x64/dotnet-gitversion /agent/_work/4/s/Myapp /output json /output buildserver
2021-08-26T21:01:22.6928074Z FATAL ERROR: v8::ToLocalChecked Empty MaybeLocal.
2021-08-26T21:01:22.6988720Z  1: node::Abort() [/agent/externals/node/bin/node]
2021-08-26T21:01:22.6996166Z  2: 0x7d027c [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7003762Z  3: v8::Utils::ReportApiFailure(char const*, char const*) [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7009398Z  4: node::SyncProcessRunner::BuildOutputArray() [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7017741Z  5: node::SyncProcessRunner::BuildResultObject() [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7025390Z  6: node::SyncProcessRunner::Spawn(v8::FunctionCallbackInfo<v8::Value> const&) [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7031412Z  7: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7038546Z  8: 0x90397e [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7046826Z  9: 0x90421e [/agent/externals/node/bin/node]
2021-08-26T21:01:22.7047486Z 10: 0x1b08956092a7
2021-08-26T21:01:23.0394482Z ##[error]Exit code 134 returned from process: file name '/agent/externals/node/bin/node', arguments '"/agent/_work/_tasks/gitversion/execute_9013cf7f-ee8d-49f4-a39b-db244928d391/0.9.10/bundle.js"'.
2021-08-26T21:01:23.0419315Z ##[debug]Microsoft.VisualStudio.Services.Agent.Util.ProcessExitCodeException: Exit code 134 returned from process: file name '/agent/externals/node/bin/node', arguments '"/agent/_work/_tasks/gitversion/execute_9013cf7f-ee8d-49f4-a39b-db244928d391/0.9.10/bundle.js"'.
   at Microsoft.VisualStudio.Services.Agent.Util.ProcessInvoker.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.ProcessInvokerWrapper.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, InputQueue`1 redirectStandardIn, Boolean inheritConsoleHandler, Boolean keepStandardInOpen, Boolean highPriorityProcess, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.DefaultStepHost.ExecuteAsync(String workingDirectory, String fileName, String arguments, IDictionary`2 environment, Boolean requireExitCodeZero, Encoding outputEncoding, Boolean killProcessOnCancel, Boolean inheritConsoleHandler, CancellationToken cancellationToken)
   at Microsoft.VisualStudio.Services.Agent.Worker.Handlers.NodeHandler.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskRunner.RunAsync()
   at Microsoft.VisualStudio.Services.Agent.Worker.StepsRunner.RunStepAsync(IStep step, CancellationToken jobCancellationToken)
2021-08-26T21:01:23.0424177Z ##[section]Finishing: GitVersion Execute
```

2 issues here.  

1.  Why is it failing?
2. Why is it failing in such a way that node isn't returning and showing the error logs so we can figure out what is going on?

Again, exact same pipeline template, works on some repos but not others.

**Comment by scphantm** [comment]
We have been experimenting.  The fix to get the pipeline rolling again has nothing to do with the variable group as we thought.  It turns out its the physical commit that makes the difference.  So when this happens, even a whitespace commit to the readme file gets the pipeline rolling again.  Any idea why we can't get a log out of this thing?

**Comment by scphantm** [comment]
we are really having a problem with this.  its bad enough where im getting pressure to pull the tool.  we show about 15% of our pipelines fail because of this error.  The problem case has expanded to include pipelines that have already worked correctly.  meaning we did the empty commit mentioned above and got it to work, then the next PR, it fails.

Any ideas here?  It really seems like node is either hanging because it doesn't like something in the repo, or, what i really think is happening is gitversion is failing for some reason and node isn't picking up the exit code or logs.  possibly because the action has it always parsing json?  if there is an error, is the return 

https://github.com/GitTools/actions/blob/d957a15d75c7fc44255d91da910f7a2c0b0be42f/src/tasks/gitversion/main.ts#L49

here, able to capture and return an error?
