### ISSUE TITLE
NullPointerException calculating base versions

### ISSUE THREAD

**Issue by dberry-rcs** [GitTools/actions#517]
I am running the gitversion github action on a repo that was migrated from perforce to git. Originally there were no tags in the repo so I added them to see if it would help. No Joy. 

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.10
        with:
          versionSpec: '5.x'
          includePrerelease: true
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Determine / Update Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.10
        with:
          additionalArguments: '/overrideconfig mode=ContinuousDeployment'

Run gittools/actions/gitversion/execute@v0.9.10
Command: dotnet-gitversion /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption /output json /output buildserver /overrideconfig mode=ContinuousDeployment
/opt/hostedtoolcache/GitVersion.Tool/5.7.0/x64/dotnet-gitversion /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption /output json /output buildserver /overrideconfig mode=ContinuousDeployment
INFO [09/02/21 20:18:15:30] Working directory: /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption
INFO [09/02/21 20:18:15:33] Branch from build environment: refs/heads/release/4.7.1
INFO [09/02/21 20:18:15:33] Project root is: /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption/
INFO [09/02/21 20:18:15:33] DotGit directory is: /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption/.git
INFO [09/02/21 20:18:15:33] Begin: Normalizing git directory for branch 'refs/heads/release/4.7.1'
  INFO [09/02/21 20:18:15:36] One remote found (origin -> 'https://github.com/ihm-software/rcs-shared-libs-passwordencryption').
  INFO [09/02/21 20:18:15:37] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [09/02/21 20:18:15:38] Updating local branch release/4.7.1 to point at fa0b8a1 change to force a build
  INFO [09/02/21 20:18:15:40] Creating local branch from remote tracking 'refs/remotes/origin/main'.
  INFO [09/02/21 20:18:15:42] Creating local branch from remote tracking 'refs/remotes/origin/release/4.8.0'.
  INFO [09/02/21 20:18:15:42] Creating local branch from remote tracking 'refs/remotes/origin/release/4.8.1'.
  INFO [09/02/21 20:18:15:42] Creating local branch from remote tracking 'refs/remotes/origin/release/4.9.0'.
  INFO [09/02/21 20:18:15:43] HEAD points at branch 'refs/heads/release/4.7.1'.
  INFO [09/02/21 20:18:15:43] End: Normalizing git directory for branch 'refs/heads/release/4.7.1' (Took: 98.73ms)
  INFO [09/02/21 20:18:15:52] Begin: Loading version variables from disk cache
    INFO [09/02/21 20:18:15:52] Cache file /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption/.git/gitversion_cache/411A6BBA83C331CB81319E1B76E0D1735C1A1645.yml not found.
  INFO [09/02/21 20:18:15:52] End: Loading version variables from disk cache (Took: 0.88ms)
  INFO [09/02/21 20:18:15:54] Using latest commit on specified branch
  INFO [09/02/21 20:18:15:57] Running against branch: release/4.7.1 (fa0b8a1 change to force a build)
  INFO [09/02/21 20:18:15:57] Begin: Calculating base versions
    INFO [09/02/21 20:18:15:59] Fallback base version: 0.1.0 with commit count source fe82e60607f48bc377cbb2e13d315ba37b25eda8
    INFO [09/02/21 20:18:15:61] Git tag 'v4.7.1': 4.7.1 with commit count source 5dea14bd82555aca09b0c2cb4cde7579cca158d5
    INFO [09/02/21 20:18:15:61] Begin: Finding branch source of 'release/4.7.1'
      INFO [09/02/21 20:18:15:62] Begin: Finding merge base between 'release/4.7.1' and 'main'.
      INFO [09/02/21 20:18:15:63] End: Finding merge base between 'release/4.7.1' and 'main'. (Took: 10.99ms)
    INFO [09/02/21 20:18:15:63] End: Finding branch source of 'release/4.7.1' (Took: 21.51ms)
  INFO [09/02/21 20:18:15:63] End: Calculating base versions (Took: 59.26ms)
  ERROR [09/02/21 20:18:15:65] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.GitObject..ctor(GitObject innerGitObject) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitObject.cs:line 12
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
   at GitVersion.GitRepository.<>c__DisplayClass27_0.<FindMergeBase>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 64
   at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`1 action)
   at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 37
   at GitVersion.GitRepository.FindMergeBase(ICommit commit, ICommit otherCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 62
   at GitVersion.RepositoryStore.FindMergeBase(IBranch branch, IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 48
   at GitVersion.RepositoryStore.<>c__DisplayClass29_0.<GetMergeCommitsForBranch>b__2(IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 454
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.RepositoryStore.GetMergeCommitsForBranch(IBranch branch, Config configuration, IEnumerable`1 excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 438
   at GitVersion.RepositoryStore.FindCommitBranchWasBranchedFrom(IBranch branch, Config configuration, IBranch[] excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 321
   at GitVersion.VersionCalculation.VersionInBranchNameVersionStrategy.GetVersions(String tagPrefixRegex, IBranch currentBranch)+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculators\VersionInBranchNameVersionStrategy.cs:line 39
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersions(IVersionStrategy strategy)+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 91
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 31
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 58
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70
  INFO [09/02/21 20:18:15:65] Attempting to show the current git graph (please include in issue): 
  INFO [09/02/21 20:18:15:65] Showing max of 100 commits
  INFO [09/02/21 20:18:15:67] * fa0b8a1 47 seconds ago  (HEAD -> release/4.7.1, origin/release/4.7.1)
* 5dea14b 57 minutes ago  (tag: v4.7.1)
* f0a0376 3 hours ago 
* 25617fb 6 hours ago 
* 3410ec7 8 hours ago 
* fe82e60 2 years, 5 months ago 
* a2750a7 3 hours ago  (tag: v5.0.0, origin/main, main)
* af3d72b 6 hours ago 
* 5792171 8 hours ago 
* 1d27f68 1 year, 1 month ago 
* 3684e55 3 years, 3 months ago 
* 804c64f 7 years ago 
* d1c1d7e 10 years ago 
* 3200ebe 10 years ago 
* 3e5e222 13 years ago 
* eacb878 13 years ago 
* 9bcb1a7 13 years ago 
* d750db8 3 hours ago  (tag: v4.8.1, origin/release/4.8.1, release/4.8.1)
* 298765b 6 hours ago 
* bf8fbc9 8 hours ago 
* bc95942 1 year, 5 months ago 
* 9f23108 3 hours ago  (tag: v4.9.0, origin/release/4.9.0, release/4.9.0)
* 9f5848d 6 hours ago 
* ad5ad67 8 hours ago 
* b16f277 1 year, 1 month ago 
* 9c06733 3 hours ago  (tag: v4.8.0, origin/release/4.8.0, release/4.8.0)
* 766b849 6 hours ago 
* 86e39ea 8 hours ago 
* 0537b26 1 year, 8 months ago 

INFO [09/02/21 20:18:15:26] Applicable build agent found: 'GitHubActions'.
INFO [09/02/21 20:18:15:30] Working directory: /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption
INFO [09/02/21 20:18:15:33] Branch from build environment: refs/heads/release/4.7.1
INFO [09/02/21 20:18:15:33] Project root is: /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption/
INFO [09/02/21 20:18:15:33] DotGit directory is: /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption/.git
INFO [09/02/21 20:18:15:33] Begin: Normalizing git directory for branch 'refs/heads/release/4.7.1'
  INFO [09/02/21 20:18:15:36] One remote found (origin -> 'https://github.com/ihm-software/rcs-shared-libs-passwordencryption').
  INFO [09/02/21 20:18:15:37] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [09/02/21 20:18:15:38] Updating local branch release/4.7.1 to point at fa0b8a1 change to force a build
  INFO [09/02/21 20:18:15:40] Creating local branch from remote tracking 'refs/remotes/origin/main'.
  INFO [09/02/21 20:18:15:42] Creating local branch from remote tracking 'refs/remotes/origin/release/4.8.0'.
  INFO [09/02/21 20:18:15:42] Creating local branch from remote tracking 'refs/remotes/origin/release/4.8.1'.
  INFO [09/02/21 20:18:15:42] Creating local branch from remote tracking 'refs/remotes/origin/release/4.9.0'.
  INFO [09/02/21 20:18:15:43] HEAD points at branch 'refs/heads/release/4.7.1'.
  INFO [09/02/21 20:18:15:43] End: Normalizing git directory for branch 'refs/heads/release/4.7.1' (Took: 98.73ms)
  INFO [09/02/21 20:18:15:52] Begin: Loading version variables from disk cache
    INFO [09/02/21 20:18:15:52] Cache file /home/runner/work/rcs-shared-libs-passwordencryption/rcs-shared-libs-passwordencryption/.git/gitversion_cache/411A6BBA83C331CB81319E1B76E0D1735C1A1645.yml not found.
  INFO [09/02/21 20:18:15:52] End: Loading version variables from disk cache (Took: 0.88ms)
  INFO [09/02/21 20:18:15:54] Using latest commit on specified branch
  INFO [09/02/21 20:18:15:57] Running against branch: release/4.7.1 (fa0b8a1 change to force a build)
  INFO [09/02/21 20:18:15:57] Begin: Calculating base versions
    INFO [09/02/21 20:18:15:59] Fallback base version: 0.1.0 with commit count source fe82e60607f48bc377cbb2e13d315ba37b25eda8
    INFO [09/02/21 20:18:15:61] Git tag 'v4.7.1': 4.7.1 with commit count source 5dea14bd82555aca09b0c2cb4cde7579cca158d5
    INFO [09/02/21 20:18:15:61] Begin: Finding branch source of 'release/4.7.1'
      INFO [09/02/21 20:18:15:62] Begin: Finding merge base between 'release/4.7.1' and 'main'.
      INFO [09/02/21 20:18:15:63] End: Finding merge base between 'release/4.7.1' and 'main'. (Took: 10.99ms)
    INFO [09/02/21 20:18:15:63] End: Finding branch source of 'release/4.7.1' (Took: 21.51ms)
  INFO [09/02/21 20:18:15:63] End: Calculating base versions (Took: 59.26ms)
  ERROR [09/02/21 20:18:15:65] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.GitObject..ctor(GitObject innerGitObject) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitObject.cs:line 12
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
   at GitVersion.GitRepository.<>c__DisplayClass27_0.<FindMergeBase>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 64
   at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`1 action)
   at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 37
   at GitVersion.GitRepository.FindMergeBase(ICommit commit, ICommit otherCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 62
   at GitVersion.RepositoryStore.FindMergeBase(IBranch branch, IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 48
   at GitVersion.RepositoryStore.<>c__DisplayClass29_0.<GetMergeCommitsForBranch>b__2(IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 454
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.RepositoryStore.GetMergeCommitsForBranch(IBranch branch, Config configuration, IEnumerable`1 excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 438
   at GitVersion.RepositoryStore.FindCommitBranchWasBranchedFrom(IBranch branch, Config configuration, IBranch[] excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 321
   at GitVersion.VersionCalculation.VersionInBranchNameVersionStrategy.GetVersions(String tagPrefixRegex, IBranch currentBranch)+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculators\VersionInBranchNameVersionStrategy.cs:line 39
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersions(IVersionStrategy strategy)+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 91
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 31
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 58
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70
  INFO [09/02/21 20:18:15:65] Attempting to show the current git graph (please include in issue): 
  INFO [09/02/21 20:18:15:65] Showing max of 100 commits
  INFO [09/02/21 20:18:15:67] * fa0b8a1 47 seconds ago  (HEAD -> release/4.7.1, origin/release/4.7.1)
* 5dea14b 57 minutes ago  (tag: v4.7.1)
* f0a0376 3 hours ago 
* 25617fb 6 hours ago 
* 3410ec7 8 hours ago 
* fe82e60 2 years, 5 months ago 
* a2750a7 3 hours ago  (tag: v5.0.0, origin/main, main)
* af3d72b 6 hours ago 
* 5792171 8 hours ago 
* 1d27f68 1 year, 1 month ago 
* 3684e55 3 years, 3 months ago 
* 804c64f 7 years ago 
* d1c1d7e 10 years ago 
* 3200ebe 10 years ago 
* 3e5e222 13 years ago 
* eacb878 13 years ago 
* 9bcb1a7 13 years ago 
* d750db8 3 hours ago  (tag: v4.8.1, origin/release/4.8.1, release/4.8.1)
* 298765b 6 hours ago 
* bf8fbc9 8 hours ago 
* bc95942 1 year, 5 months ago 
* 9f23108 3 hours ago  (tag: v4.9.0, origin/release/4.9.0, release/4.9.0)
* 9f5848d 6 hours ago 
* ad5ad67 8 hours ago 
* b16f277 1 year, 1 month ago 
* 9c06733 3 hours ago  (tag: v4.8.0, origin/release/4.8.0, release/4.8.0)
* 766b849 6 hours ago 
* 86e39ea 8 hours ago 
* 0537b26 1 year, 8 months ago 

  INFO [09/02/21 20:18:15:69] Done writing 
Error: Error: The process '/opt/hostedtoolcache/GitVersion.Tool/5.7.0/x64/dotnet-gitversion' failed with exit code 1

**Comment by dberry-rcs** [comment]
same issue when I run it from the commandline

C:\Users\DBerry\Projects\rcs-shared-libs-passwordencryption>dotnet-gitversion
INFO [09/02/21 16:59:32:40] Working directory: C:\Users\DBerry\Projects\rcs-shared-libs-passwordencryption
INFO [09/02/21 16:59:32:42] Project root is: C:\Users\DBerry\Projects\rcs-shared-libs-passwordencryption\
INFO [09/02/21 16:59:32:42] DotGit directory is: C:\Users\DBerry\Projects\rcs-shared-libs-passwordencryption\.git
INFO [09/02/21 16:59:32:45] Begin: Loading version variables from disk cache
  INFO [09/02/21 16:59:32:45] Cache file C:\Users\DBerry\Projects\rcs-shared-libs-passwordencryption\.git\gitversion_cache\079DB91D8F2A7168D280512C34DABB9A59435456.yml not found.
  INFO [09/02/21 16:59:32:45] End: Loading version variables from disk cache (Took: 1.00ms)
  INFO [09/02/21 16:59:32:46] Using latest commit on specified branch
  INFO [09/02/21 16:59:32:49] Running against branch: release/4.7.1 (876cad5 change back to 5.x for gitversion and disallow betas)
  INFO [09/02/21 16:59:32:50] Begin: Calculating base versions
    INFO [09/02/21 16:59:32:51] Fallback base version: 0.1.0 with commit count source fe82e60607f48bc377cbb2e13d315ba37b25eda8
    INFO [09/02/21 16:59:32:52] Git tag 'v4.7.1': 4.7.1 with commit count source 5dea14bd82555aca09b0c2cb4cde7579cca158d5
    INFO [09/02/21 16:59:32:53] Begin: Finding branch source of 'release/4.7.1'
      INFO [09/02/21 16:59:32:54] Begin: Finding merge base between 'release/4.7.1' and 'main'.
      INFO [09/02/21 16:59:32:55] End: Finding merge base between 'release/4.7.1' and 'main'. (Took: 11.94ms)
    INFO [09/02/21 16:59:32:55] End: Finding branch source of 'release/4.7.1' (Took: 22.20ms)
  INFO [09/02/21 16:59:32:55] End: Calculating base versions (Took: 51.84ms)
  ERROR [09/02/21 16:59:32:56] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at GitVersion.GitObject..ctor(GitObject innerGitObject) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitObject.cs:line 12
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
   at GitVersion.GitRepository.<>c__DisplayClass27_0.<FindMergeBase>b__0() in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 64
   at Polly.Policy`1.<>c__DisplayClass11_0.<Execute>b__0(Context ctx, CancellationToken ct)
   at Polly.Retry.RetryEngine.Implementation[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Action`4 onRetry, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider)
   at Polly.Retry.RetryPolicy`1.Implementation(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`3 action, Context context, CancellationToken cancellationToken)
   at Polly.Policy`1.Execute(Func`1 action)
   at GitVersion.Helpers.RetryAction`2.Execute(Func`1 operation) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Helpers\RetryAction.cs:line 37
   at GitVersion.GitRepository.FindMergeBase(ICommit commit, ICommit otherCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\GitRepository.cs:line 62
   at GitVersion.RepositoryStore.FindMergeBase(IBranch branch, IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 48
   at GitVersion.RepositoryStore.<>c__DisplayClass29_0.<GetMergeCommitsForBranch>b__2(IBranch otherBranch) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 454
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.OrderedEnumerable`1.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.RepositoryStore.GetMergeCommitsForBranch(IBranch branch, Config configuration, IEnumerable`1 excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 438
   at GitVersion.RepositoryStore.FindCommitBranchWasBranchedFrom(IBranch branch, Config configuration, IBranch[] excludedBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\RepositoryStore.cs:line 321
   at GitVersion.VersionCalculation.VersionInBranchNameVersionStrategy.GetVersions(String tagPrefixRegex, IBranch currentBranch)+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculators\VersionInBranchNameVersionStrategy.cs:line 39
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersions(IVersionStrategy strategy)+MoveNext() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 91
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GitVersion.VersionCalculation.BaseVersionCalculator.GetBaseVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\BaseVersionCalculator.cs:line 31
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 58
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 70
  INFO [09/02/21 16:59:32:56] Attempting to show the current git graph (please include in issue):
  INFO [09/02/21 16:59:32:56] Showing max of 100 commits
  INFO [09/02/21 16:59:32:64] * 876cad5 15 minutes ago  (HEAD -> release/4.7.1, origin/release/4.7.1)
* 51a0e80 17 minutes ago
* d597894 31 minutes ago
* fa0b8a1 42 minutes ago
* 5dea14b 2 hours ago  (tag: v4.7.1, updateProject)
* f0a0376 3 hours ago
* 25617fb 7 hours ago  (p4/4.7.1.0)
* 3410ec7 9 hours ago
* fe82e60 2 years, 5 months ago
* a2750a7 3 hours ago  (tag: v5.0.0, origin/main, main)
* af3d72b 7 hours ago  (p4/main, p4/HEAD)
* 5792171 9 hours ago
* 1d27f68 1 year, 1 month ago
* 3684e55 3 years, 3 months ago
* 804c64f 7 years ago
* d1c1d7e 10 years ago
* 3200ebe 10 years ago
* 3e5e222 13 years ago
* eacb878 13 years ago
* 9bcb1a7 13 years ago
* d750db8 3 hours ago  (tag: v4.8.1, origin/release/4.8.1, release/4.8.1)
* 298765b 7 hours ago  (p4/4.8.1.0)
* bf8fbc9 9 hours ago
* bc95942 1 year, 5 months ago
* 9f23108 3 hours ago  (tag: v4.9.0, origin/release/4.9.0, release/4.9.0)
* 9f5848d 7 hours ago  (p4/4.9.0.0)
* ad5ad67 9 hours ago
* b16f277 1 year, 1 month ago
* 9c06733 3 hours ago  (tag: v4.8.0, origin/release/4.8.0, release/4.8.0)
* 766b849 7 hours ago  (p4/4.8.0.0)
* 86e39ea 9 hours ago
* 0537b26 1 year, 8 months ago

**Comment by dberry-rcs** [comment]
It works fine for main, but does not work for any of the branches

C:\Users\DBerry\Projects\rcs-shared-libs-passwordencryption>dotnet-gitversion
{
  "Major": 5,
  "Minor": 0,
  "Patch": 0,
  "PreReleaseTag": "",
  "PreReleaseTagWithDash": "",
  "PreReleaseLabel": "",
  "PreReleaseLabelWithDash": "",
  "PreReleaseNumber": null,
  "WeightedPreReleaseNumber": 60000,
  "BuildMetaData": null,
  "BuildMetaDataPadded": "",
  "FullBuildMetaData": "Branch.main.Sha.a2750a7e512107d21f48a3618aff64bace2ea4ea",
  "MajorMinorPatch": "5.0.0",
  "SemVer": "5.0.0",
  "LegacySemVer": "5.0.0",
  "LegacySemVerPadded": "5.0.0",
  "AssemblySemVer": "5.0.0.0",
  "AssemblySemFileVer": "5.0.0.0",
  "FullSemVer": "5.0.0",
  "InformationalVersion": "5.0.0+Branch.main.Sha.a2750a7e512107d21f48a3618aff64bace2ea4ea",
  "BranchName": "main",
  "EscapedBranchName": "main",
  "Sha": "a2750a7e512107d21f48a3618aff64bace2ea4ea",
  "ShortSha": "a2750a7",
  "NuGetVersionV2": "5.0.0",
  "NuGetVersion": "5.0.0",
  "NuGetPreReleaseTagV2": "",
  "NuGetPreReleaseTag": "",
  "VersionSourceSha": "a2750a7e512107d21f48a3618aff64bace2ea4ea",
  "CommitsSinceVersionSource": 0,
  "CommitsSinceVersionSourcePadded": "0000",
  "UncommittedChanges": 0,
  "CommitDate": "2021-09-02"
}

**Comment by dberry-rcs** [comment]
More info. Even though the branch structure was created correctly, the branches had unrelated histories with main. Shouldn't gitversion, revert to treating the branch as a single entity and still provide version info rather than an NPE because it could not find a common base version?
