### ISSUE TITLE
Having trouble using gittools/actions/gitversion/execute@v0.9.13 for Node.JS pipeline

### ISSUE THREAD

**Issue by TheMagnificent11** [GitTools/actions#647]
I've got the following GitHub action.

```
name: Node.js CI

...

jobs:
  ...
  package:
    needs: [build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.13
      with:
        versionSpec: '5.9.0'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.13
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml

  ...
```

This is the contents of `GitVersion.yml`
```
mode: ContinuousDeployment
assembly-versioning-scheme: MajorMinorPatch
assembly-file-versioning-scheme: MajorMinorPatchTag
assembly-informational-format: '{InformationalVersion}'
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
commit-message-incrementing: Enabled
ignore:
  sha: []
```

This is the error I get when running the GitHub action.
```
Run gittools/actions/gitversion/execute@v0.9.13
Command: dotnet-gitversion /home/runner/work/{{redacted}} /output json /output buildserver /config GitVersion.yml
/opt/hostedtoolcache/GitVersion.Tool/5.9.0/x64/dotnet-gitversion /home/runner/work/{{redacted}} /output json /output buildserver /config GitVersion.yml
INFO [03/28/22 4:10:52:92] Working directory: /home/runner/work/{{redacted}}
INFO [03/28/22 4:10:52:94] Branch from build environment: refs/pull/3/merge
INFO [03/28/22 4:10:52:94] Project root is: /home/runner/work/{{redacted}}
INFO [03/28/22 4:10:52:94] DotGit directory is: /home/runner/work/{{redacted}}/.git
INFO [03/28/22 4:10:52:94] Begin: Normalizing git directory for branch 'refs/pull/3/merge'
  INFO [03/28/22 4:10:52:96] One remote found (origin -> 'https://github.com/TheMagnificent[11](https://{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:11)/{{redacted}}').
  INFO [03/28/22 4:10:52:97] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [03/28/22 4:10:52:97] Creating local branch pull/3/merge pointing at 1969bf7
  INFO [03/28/22 4:10:53:00] HEAD points at branch 'refs/heads/pull/3/merge'.
  INFO [03/28/22 4:10:53:00] End: Normalizing git directory for branch 'refs/pull/3/merge' (Took: 67.29ms)
  INFO [03/28/22 4:10:53:01] Begin: Loading version variables from disk cache
    INFO [03/28/22 4:10:53:01] Cache file /home/runner/work/{{redacted}}/.git/gitversion_cache/5EAF0FEC6E8ED4591D550690D9EA416C86FBBD5D.yml not found.
  INFO [03/28/22 4:10:53:01] End: Loading version variables from disk cache (Took: 0.51ms)
  INFO [03/28/22 4:10:53:01] Using latest commit on specified branch
  INFO [03/28/22 4:10:53:10] Begin: Attempting to inherit branch configuration from parent branch
  INFO [03/28/22 4:10:53:10] End: Attempting to inherit branch configuration from parent branch (Took: 4.35ms)
  ERROR [03/28/22 4:10:53:18] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 286
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line [15](https://{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:15)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 38
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [03/28/22 4:10:53:18] Attempting to show the current git graph (please include in issue): 
  INFO [03/28/22 4:10:53:18] Showing max of 100 commits
  INFO [03/28/22 4:10:53:25] * 1969bf7 79 seconds ago  (grafted, HEAD -> pull/3/merge, pull/3/merge)

INFO [03/28/22 4:10:52:87] Applicable build agent found: 'GitHubActions'.
INFO [03/28/22 4:10:52:92] Working directory: /home/runner/work/{{redacted}}
INFO [03/28/22 4:10:52:94] Branch from build environment: refs/pull/3/merge
INFO [03/28/22 4:10:52:94] Project root is: /home/runner/work/{{redacted}}
INFO [03/28/22 4:10:52:94] DotGit directory is: /home/runner/work/{{redacted}}/.git
INFO [03/28/22 4:10:52:94] Begin: Normalizing git directory for branch 'refs/pull/3/merge'
  INFO [03/28/22 4:10:52:96] One remote found (origin -> 'https://{{redacted}}').
  INFO [03/28/22 4:10:52:97] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [03/28/22 4:10:52:97] Creating local branch pull/3/merge pointing at 1969bf7
  INFO [03/28/22 4:10:53:00] HEAD points at branch 'refs/heads/pull/3/merge'.
  INFO [03/28/22 4:10:53:00] End: Normalizing git directory for branch 'refs/pull/3/merge' (Took: 67.29ms)
  INFO [03/28/22 4:10:53:01] Begin: Loading version variables from disk cache
    INFO [03/28/22 4:10:53:01] Cache file /home/runner/work/{{redacted}}/.git/gitversion_cache/5EAF0FEC6E8ED4591D550690D9EA4[16](https://{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:16)C86FBBD5D.yml not found.
  INFO [03/28/22 4:10:53:01] End: Loading version variables from disk cache (Took: 0.51ms)
  INFO [03/28/22 4:10:53:01] Using latest commit on specified branch
  INFO [03/28/22 4:10:53:10] Begin: Attempting to inherit branch configuration from parent branch
  INFO [03/28/22 4:10:53:10] End: Attempting to inherit branch configuration from parent branch (Took: 4.35ms)
  ERROR [03/28/22 4:10:53:[18](https://{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:18)] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 286
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 15
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 38
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [03/28/22 4:10:53:18] Attempting to show the current git graph (please include in issue): 
  INFO [03/28/22 4:10:53:18] Showing max of 100 commits
  INFO [03/28/22 4:10:53:25] * [19](https://{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:19)69bf7 79 seconds ago  (grafted, HEAD -> pull/3/merge, pull/3/merge)

  INFO [03/28/[22](https://{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:22) 4:10:53:[27](https:/{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:27)] Done writing 
Error: Error: The process '/opt/hostedtoolcache/GitVersion.Tool/5.9.0/x[64](https://{{redacted}}/runs/5714441943?check_suite_focus=true#step:4:64)/dotnet-gitversion' failed with exit code 1
```

This same GitVersion action code works in another repository where the source being built is .Net 6.

**Comment by TheMagnificent11** [comment]
> I had the same problem in a school project.
> 
> Try add fetch depth in the checkout options. This should fetch all history, branches & commits.
> 
> ```yaml
> - uses: actions/checkout@v3
>   with:
>     fetch-depth: 0
> ```

Thanks, that worked
