### ISSUE TITLE
Null Reference Exception

### ISSUE THREAD

**Issue by seanarmstrong87** [GitTools/actions#735]
I am using the azure pipeline task, in a linux pipeline. 

These are my setup and execute tasks:

```yaml
          - task: gitversion/setup@0
            displayName: Setup GitVersion
            inputs:
              versionSpec: '5.x'
          
          - task: gitversion/execute@0
            displayName: Use GitVersion
```

Output of the setup task is:
```
--------------------------
Installing GitVersion.Tool version 5.x
--------------------------
Found tool in cache: GitVersion.Tool 5.10.3 x64
Prepending PATH environment variable with directory: /agent/_work/_tool/GitVersion.Tool/5.10.3/x64
```

This is the error I get on the execute task:

  ```
INFO [09/15/22 12:57:39:79] One remote found (origin -> '...hidden...').
  INFO [09/15/22 12:57:39:79] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [09/15/22 12:57:39:80] Creating local branch pull/6711/merge pointing at b303912
  INFO [09/15/22 12:57:39:82] Creating local branch from remote tracking 'refs/remotes/origin/003ee501611dbde37c4dead0a42067e2b1607a37'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/28af626f8bbcc78ef95b0007077f679bce8ab23b'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/48ac2dcb5313429bb2c061fd7b13e618f0fed543'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/7ac7d9d562cf196cb8feab7671a61d07394e7e6f'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/a0484ea785c4f329d50d6494be95edbd6cd9a42e'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/b30391225f04c5c50134246bdc7da3824d240261'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/c895a9f2c17721a07070a56be2eff6775d232be7'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/db9c3fd68e5f06d0364428878fb48b0692d86d7b'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/ef89bddaf21cfb66f9e627511661775b2c38d672'.
  INFO [09/15/22 12:57:39:83] Creating local branch from remote tracking 'refs/remotes/origin/f550339972a1eaad4040cb3c6a7fa12267c68f9d'.
  INFO [09/15/22 12:57:39:84] HEAD points at branch 'refs/heads/pull/6711/merge'.
  INFO [09/15/22 12:57:39:84] End: Normalizing git directory for branch 'refs/pull/6711/merge' (Took: 72.06ms)
INFO [09/15/22 12:57:39:84] Begin: Loading version variables from disk cache
    INFO [09/15/22 12:57:39:84] Cache file /agent/_work/4/s/.git/gitversion_cache/CDDA8C83040A07ABA0D539B864DDE60E9AFCEAEC.yml not found.
  INFO [09/15/22 12:57:39:84] End: Loading version variables from disk cache (Took: 0.31ms)
  INFO [09/15/22 12:57:39:85] Using latest commit on specified branch
  INFO [09/15/22 12:57:39:86] Begin: Attempting to inherit branch configuration from parent branch
  INFO [09/15/22 12:57:39:87] End: Attempting to inherit branch configuration from parent branch (Took: 4.16ms)
  ERROR [09/15/22 12:57:39:88] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 289
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 17
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 39
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [09/15/22 12:57:39:88] Attempting to show the current git graph (please include in issue): 
  INFO [09/15/22 12:57:39:88] Showing max of 100 commits
  INFO [09/15/22 12:57:39:90] * b303912 19 seconds ago  (grafted, HEAD -> pull/6711/merge, origin/b30391225f04c5c50134246bdc7da3824d240261, b30391225f04c5c50134246bdc7da3824d240261)
```

If I use this instead for the execute task then it works but none of the environment variable are found:

```yaml
          - task: gitversion/execute@0
            displayName: Use GitVersion
            inputs:
              updateAssemblyInfo: true
              additionalArguments: '/showConfig'
```

Is anyone able to help with this problem?

**Comment by seanarmstrong87** [comment]
I tried using the command line tool inside the pipeline instead setup like this:

```
          - script: 'dotnet tool install --global GitVersion.Tool --version 5.*'
            
          - script: 'dotnet-gitversion'
```

But get the same error:
```
INFO [09/15/22 14:39:58:73] Skipping fetching, if GitVersion does not calculate your version as expected you might need to allow fetching or use dynamic repositories
  INFO [09/15/22 14:39:58:73] Creating local branch pull/6711/merge pointing at 4bd54c4
  INFO [09/15/22 14:39:58:76] Creating local branch from remote tracking 'refs/remotes/origin/4bd54c4b667aa2bf005babeb4d4a10555fc0c922'.
  INFO [09/15/22 14:39:58:76] Creating local branch from remote tracking 'refs/remotes/origin/7467651d946bece9a3660cc1997402c195a8f025'.
  INFO [09/15/22 14:39:58:76] HEAD points at branch 'refs/heads/pull/6711/merge'.
  INFO [09/15/22 14:39:58:76] End: Normalizing git directory for branch 'refs/pull/6711/merge' (Took: 69.21ms)
  INFO [09/15/22 14:39:58:77] Begin: Loading version variables from disk cache
    INFO [09/15/22 14:39:58:77] Cache file /agent/_work/1/s/.git/gitversion_cache/69FB3259E659D8974C4C2C199A931DC9AE1CC7C4.yml not found.
  INFO [09/15/22 14:39:58:77] End: Loading version variables from disk cache (Took: 0.23ms)
  INFO [09/15/22 14:39:58:77] Using latest commit on specified branch
  INFO [09/15/22 14:39:58:80] Begin: Attempting to inherit branch configuration from parent branch
  INFO [09/15/22 14:39:58:80] End: Attempting to inherit branch configuration from parent branch (Took: 4.73ms)
  ERROR [09/15/22 14:39:58:81] An unexpected error occurred:
System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 289
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.LibGit2Sharp.Core.LazyGroup<T>.IEvaluator<TInput>.Evaluate(TInput input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 88
   at LibGit2Sharp.Core.LazyGroup`1.<Evaluate>b__6_0(T input) in /_/LibGit2Sharp/Core/LazyGroup.cs:line 36
   at LibGit2Sharp.Core.GitObjectLazyGroup.EvaluateInternal(Action`1 evaluator) in /_/LibGit2Sharp/Core/GitObjectLazyGroup.cs:line 20
   at LibGit2Sharp.Core.LazyGroup`1.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 34
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.Evaluate() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 80
   at LibGit2Sharp.Core.LazyGroup`1.Dependent`2.get_Value() in /_/LibGit2Sharp/Core/LazyGroup.cs:line 73
   at LibGit2Sharp.Commit.get_Committer() in /_/LibGit2Sharp/Commit.cs:line 87
   at GitVersion.Commit..ctor(Commit innerCommit) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 17
   at GitVersion.Commit.<>c.<.ctor>b__3_0(Commit parent) in D:\a\GitVersion\GitVersion\src\GitVersion.LibGit2Sharp\Git\Commit.cs:line 16
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at GitVersion.Configuration.BranchConfigurationCalculator.InheritBranchConfiguration(Int32 recursions, IBranch targetBranch, BranchConfig branchConfiguration, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 77
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfigurationInternal(Int32 recursions, IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 54
   at GitVersion.Configuration.BranchConfigurationCalculator.GetBranchConfiguration(IBranch targetBranch, ICommit currentCommit, Config configuration, IList`1 excludedInheritBranches) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Configuration\BranchConfigurationCalculator.cs:line 28
   at GitVersion.GitVersionContextFactory.Create(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionContextFactory.cs:line 39
   at GitVersion.GitVersionCoreModule.<>c__DisplayClass0_0.<RegisterTypes>b__1() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\GitVersionCoreModule.cs:line 37
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at GitVersion.VersionCalculation.NextVersionCalculator.get_context() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 15
   at GitVersion.VersionCalculation.NextVersionCalculator.FindVersion() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\VersionCalculation\NextVersionCalculator.cs:line 30
   at GitVersion.GitVersionCalculateTool.CalculateVersionVariables() in D:\a\GitVersion\GitVersion\src\GitVersion.Core\Core\GitVersionCalculateTool.cs:line 52
   at GitVersion.GitVersionExecutor.RunGitVersionTool(GitVersionOptions gitVersionOptions) in D:\a\GitVersion\GitVersion\src\GitVersion.App\GitVersionExecutor.cs:line 66
  INFO [09/15/22 14:39:58:81] Attempting to show the current git graph (please include in issue): 
  INFO [09/15/22 14:39:58:81] Showing max of 100 commits
  INFO [09/15/22 14:39:58:84] * 4bd54c4 25 seconds ago  (grafted, HEAD -> pull/6711/merge, origin/4bd54c4b667aa2bf005babeb4d4a10555fc0c922, 4bd54c4b667aa2bf005babeb4d4a10555fc0c922)
* 7467651 14 minutes ago  (grafted, origin/7467651d946bece9a3660cc1997402c195a8f025, 7467651d946bece9a3660cc1997402c195a8f025)
```

**Comment by seanarmstrong87** [comment]
FYI I got this working in the end by adding fetchDepth to the checkout command
```
          - checkout: self
            persistCredentials: true
            fetchDepth: 0
```

**Comment by arturcic** [comment]
@seanarmstrong87 do you mind adding this to the examples in the docs? So that it's clear we need to fetch the entire history, thanks

**Comment by seanarmstrong87** [comment]
There is a PR there with a note added to the docs. I am not familiar with github PR process so hope it's ok
