### ISSUE TITLE
gitversion/execute@0 throws exception in Azure Pipelines.

### ISSUE THREAD

**Issue by bauca** [GitTools/actions#863]
**Reproduction steps:**

A pipeline is defined as such:

```
trigger: none

stages:
  - stage: TestStage
    jobs:
    - job: Job1      
      steps:      
        - checkout: self
          clean: true
          persistCredentials: true  
        - task: gitversion/setup@0
          displayName: Install GitVersion
          inputs:
            versionSpec: '5.x'
            preferLatestVersion: true
        - script: |
            ls -ltra
          workingDirectory: '$(Pipeline.Workspace)/s'
          displayName: Debugger 
        - task: gitversion/execute@0
          displayName: Determine Version
          name: version
          inputs:
            useConfigFile: true     
            configFilePath: '$(Pipeline.Workspace)/s/GitVersion.yml'
        - script: |
            echo "Major: $(version.major)"
            echo "Minor: $(version.minor)"
            echo "Patch: $(version.patch)"
            echo "PreReleaseTag: $(version.preReleaseTag)"
            echo "PreReleaseTagWithDash: $(version.preReleaseTagWithDash)"
            echo "PreReleaseLabel: $(version.preReleaseLabel)"
            echo "PreReleaseNumber: $(version.preReleaseNumber)"
            echo "WeightedPreReleaseNumber: $(version.weightedPreReleaseNumber)"
            echo "BuildMetaData: $(version.buildMetaData)"
            echo "BuildMetaDataPadded: $(version.buildMetaDataPadded)"
            echo "FullBuildMetaData: $(version.fullBuildMetaData)"
            echo "MajorMinorPatch: $(version.majorMinorPatch)"
            echo "SemVer: $(version.semVer)"
            echo "LegacySemVer: $(version.legacySemVer)"
            echo "LegacySemVerPadded: $(version.legacySemVerPadded)"
            echo "AssemblySemVer: $(version.assemblySemVer)"
            echo "AssemblySemFileVer: $(version.assemblySemFileVer)"
            echo "FullSemVer: $(version.fullSemVer)"
            echo "InformationalVersion: $(version.informationalVersion)"
            echo "BranchName: $(version.branchName)"
            echo "EscapedBranchName: $(version.escapedBranchName)"
            echo "Sha: $(version.sha)"
            echo "ShortSha: $(version.shortSha)"
            echo "NuGetVersionV2: $(version.nuGetVersionV2)"
            echo "NuGetVersion: $(version.nuGetVersion)"
            echo "NuGetPreReleaseTagV2: $(version.nuGetPreReleaseTagV2)"
            echo "NuGetPreReleaseTag: $(version.nuGetPreReleaseTag)"
            echo "VersionSourceSha: $(version.versionSourceSha)"
            echo "CommitsSinceVersionSource: $(version.commitsSinceVersionSource)"
            echo "CommitsSinceVersionSourcePadded: $(version.commitsSinceVersionSourcePadded)"
            echo "UncommittedChanges: $(version.uncommittedChanges)"
            echo "CommitDate: $(version.commitDate)"
          displayName: Display GitVersion outputs (step output)
        - script: |
            git fetch
            git checkout main
            git pull            
            git tag 1.0.0
            git push --set-upstream origin main 1.0.0
            git tag -n
          displayName: "Tagging the main branch"
```

**And a GitVersion.yml file as such:**

```
mode: Mainline
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
update-build-number: false
branches:
  main:
    source-branches: [ 'main' ]
    is-mainline: true
```

**Expected result:**
Task runs successfully

**Current results:**

```
Starting: Determine Version
==============================================================================
Task         : Execute GitVersion Task
Description  : Easy Semantic Versioning (http://semver.org/) for projects using Git
Version      : 0.10.2
Author       : GitTools Contributors
Help         : See the [documentation](https://gitversion.net/docs/) for help
==============================================================================
Agent: 'Azure Pipelines'
Command: dotnet-gitversion /home/vsts/work/1/s /output json /output buildserver /config /home/vsts/work/1/s/GitVersion.yml
/opt/hostedtoolcache/GitVersion.Tool/5.12.0/x64/dotnet-gitversion /home/vsts/work/1/s /output json /output buildserver /config /home/vsts/work/1/s/GitVersion.yml
  ERROR [05/06/23 18:26:06:06] An unexpected error occurred:
INFO [05/06/23 18:26:05:84] Working directory: /home/vsts/work/1/s
System.NullReferenceException: Object reference not set to an instance of an object.
INFO [05/06/23 18:26:05:85] Project root is: /home/vsts/work/1/s/
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle) in /_/LibGit2Sharp/Core/Handles/Objects.cs:line 509
INFO [05/06/23 18:26:05:85] DotGit directory is: /home/vsts/work/1/s/.git
   at LibGit2Sharp.Core.Proxy.git_commit_author(ObjectHandle obj) in /_/LibGit2Sharp/Core/Proxy.cs:line 289
```

* The rest of the exception was omitted for simplicity.

**Comment by arturcic** [comment]
When you clone can you specify the depth 0?

```yaml
steps:
  - checkout: self
    fetchDepth: 0
```

I think you missed the section in the docs

https://github.com/GitTools/actions/blob/main/docs/examples/azure/gitversion/setup/usage-examples.md#usage-examples
