### ISSUE TITLE
GitReleaseManager - Unable to locate input file

### ISSUE THREAD

**Issue by damienbutt** [GitTools/actions#897]
Hi all,

I'm trying to get the GitReleaseManager GH Action working but having trouble.

My workflow steps look like this:

```yaml
- name: Install GitReleaseManager
  uses: gittools/actions/gitreleasemanager/setup@v0
  with:
    versionSpec: "0.13.x"

- name: Create Release with GitReleaseManager
  uses: gittools/actions/gitreleasemanager/create@v0
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    owner: ${{ github.repository_owner }}
    repository: ${{ github.repository }}
```

The installation completes without error but on trying to create a release I am getting the following error:

```
Command: dotnet-gitreleasemanager create --owner Norgate-AV-Solutions-Ltd --repository Norgate-AV-Solutions-Ltd/gh-actions-playground --token *** --targetDirectory C:/actions-runner/_work/gh-actions-playground/gh-actions-playground
C:\actions-runner\_work\_tool\GitReleaseManager.Tool\0.13.0\x64\dotnet-gitreleasemanager.exe create --owner Norgate-AV-Solutions-Ltd --repository Norgate-AV-Solutions-Ltd/gh-actions-playground --token *** --targetDirectory C:/actions-runner/_work/gh-actions-playground/gh-actions-playground

   ____ _ _   ____      _                     __  __
  / ___(_) |_|  _ \ ___| | ___  __ _ ___  ___|  \/  | __ _ _ __   __ _  __ _  ___ _ __
 | |  _| | __| |_) / _ \ |/ _ \/ _` / __|/ _ \ |\/| |/ _` | '_ \ / _` |/ _` |/ _ \ '__|
 | |_| | | |_|  _ <  __/ |  __/ (_| \__ \  __/ |  | | (_| | | | | (_| | (_| |  __/ |
  \____|_|\__|_| \_\___|_|\___|\__,_|___/\___|_|  |_|\__,_|_| |_|\__,_|\__, |\___|_|
                                                                       |___/
                                                                                 0.13.0

Creating release...
[FTL] Unable to locate input file.
System.IO.FileNotFoundException: Unable to locate input file.
   at GitReleaseManager.Core.Ensure.FileExists(String path, String message) in /_/src/GitReleaseManager.Core/Ensure.cs:line 46
   at GitReleaseManager.Core.VcsService.CreateReleaseFromInputFileAsync(String owner, String repository, String name, String inputFilePath, String targetCommitish, IList`1 assets, Boolean prerelease) in /_/src/GitReleaseManager.Core/VcsService.cs:line 63
   at GitReleaseManager.Core.Commands.CreateCommand.Execute(CreateSubOptions options) in /_/src/GitReleaseManager.Core/Commands/CreateCommand.cs:line 46
   at GitReleaseManager.Cli.Program.Main(String[] args) in /_/src/GitReleaseManager.Cli/Program.cs:line 34
Error: The process 'C:\actions-runner\_work\_tool\GitReleaseManager.Tool\0.13.0\x64\dotnet-gitreleasemanager.exe' failed with exit code 1
```

According to the docs the only required params are the "token", "owner", and "repository". I have tried adding an "inputFilePath" param but to be honest I am unsure what this is supposed to be.

Is anyone able to assist?

The environment details are below. It's a self-hosted runner on Windows Server.

```pwsh
Name                           Value
----                           -----
PSVersion                      7.2.11
PSEdition                      Core
GitCommitId                    7.2.11
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

Drive        : C
Provider     : Microsoft.PowerShell.Core\FileSystem
ProviderPath : C:\actions-runner\_work\gh-actions-playground\gh-actions-playground
Path         : C:\actions-runner\_work\gh-actions-playground\gh-actions-playground

Path:
C:\Program Files\PowerShell\7;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\Common Files\AMXShare\COM;C:\Program Files\PowerShell\7\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Administrator.INTERNAL\scoop\apps\python\current\Scripts;C:\Users\Administrator.INTERNAL\scoop\apps\python\current;C:\Users\Administrator.INTERNAL\scoop\apps\openjdk\current\bin;C:\Users\Administrator.INTERNAL\scoop\apps\nodejs-lts\current\bin;C:\Users\Administrator.INTERNAL\scoop\apps\nodejs-lts\current;C:\Users\Administrator.INTERNAL\go\bin;C:\Users\Administrator.INTERNAL\scoop\apps\gnupg\current\bin;C:\Users\Administrator.INTERNAL\scoop\apps\yarn\current\global\node_modules\.bin;C:\Users\Administrator.INTERNAL\scoop\apps\yarn\current\bin;C:\Users\Administrator.INTERNAL\scoop\apps\yarn\current\global\bin;C:\Users\Administrator.INTERNAL\scoop\apps\pyenv\current\pyenv-win\shims;C:\Users\Administrator.INTERNAL\scoop\shims;C:\Users\Administrator.INTERNAL\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator.INTERNAL\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Administrator.INTERNAL\.dotnet\tools;C:\Users\Administrator.INTERNAL\AppData\Local\Microsoft\WindowsApps

whoami:
internal\administrator

Default Environment Variables:
CI: true
GITHUB_ACTION: __run
GITHUB_ACTION_PATH: 
GITHUB_ACTION_REPOSITORY: 
GITHUB_ACTIONS: true
GITHUB_ACTOR: damienbutt
GITHUB_ACTOR_ID: 22627489
GITHUB_API_URL: https://api.github.com/
GITHUB_BASE_REF: 
GITHUB_ENV: C:\actions-runner\_work\_temp\_runner_file_commands\set_env_523ae106-b5a4-42f5-826c-45e547f5f05d
GITHUB_EVENT_NAME: push
GITHUB_EVENT_PATH: C:\actions-runner\_work\_temp\_github_workflow\event.json
GITHUB_GRAPHQL_URL: https://api.github.com/graphql
GITHUB_HEAD_REF: 
GITHUB_JOB: build
GITHUB_PATH: C:\actions-runner\_work\_temp\_runner_file_commands\add_path_523ae106-b5a4-42f5-826c-45e547f5f05d
GITHUB_REF: refs/heads/master
GITHUB_REF_NAME: master
GITHUB_REF_PROTECTED: false
GITHUB_REF_TYPE: branch
GITHUB_REPOSITORY: Norgate-AV-Solutions-Ltd/gh-actions-playground
GITHUB_REPOSITORY_ID: 477931785
GITHUB_REPOSITORY_OWNER: Norgate-AV-Solutions-Ltd
GITHUB_REPOSITORY_OWNER_ID: 22775536
GITHUB_RETENTION_DAYS: 90
GITHUB_RUN_ATTEMPT: 1
GITHUB_RUN_ID: 5248964935
GITHUB_RUN_NUMBER: 21
GITHUB_SERVER_URL: https://github.com/
GITHUB_SHA: fbdcfe781e63f715d5c2f2703a7f5585ff04d6d6
GITHUB_STEP_SUMMARY: C:\actions-runner\_work\_temp\_runner_file_commands\step_summary_523ae106-b5a4-42f5-826c-45e547f5f05d
GITHUB_WORKFLOW: CI
GITHUB_WORKFLOW_REF: Norgate-AV-Solutions-Ltd/gh-actions-playground/.github/workflows/main.yml@refs/heads/master
GITHUB_WORKFLOW_SHA: fbdcfe781e63f715d5c2f2703a7f5585ff04d6d6
GITHUB_WORKSPACE: C:\actions-runner\_work\gh-actions-playground\gh-actions-playground
RUNNER_ARCH: X64
RUNNER_DEBUG: 
RUNNER_NAME: GH-RUNNER-02
RUNNER_OS: Windows
RUNNER_TEMP: C:\actions-runner\_work\_temp
RUNNER_TOOL_CACHE: C:\actions-runner\_work\_tool
```

Thanks,

D

**Comment by arturcic** [comment]
@damienbutt the actions are just calling the gitreleasemanager tool. According to the code that gets executed https://github.com/GitTools/GitReleaseManager/blob/c0d8b8e4dd54e72c22126971b7fc2b44855c8e99/src/GitReleaseManager.Core/Commands/CreateCommand.cs#L44 you either specify a milestone for which you create the release notes or you provide the release notes. If you specify the milestone, it will use the issues and PRS that are included in the milestone. In the docs the example shows how to use the milestone
